### ISSUE TITLE
Part 5 Attachments has extra properties

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#102]
Previous parts don't have

```
      multiPartPrefix: "OSLC Core",
      partNumber: 5,
```

What do they do?

**Comment by jamsden** [comment]
I don't remember for sure, but that might be something I was experimenting with to have ReSpec generate the part file names OASIS required. If we can just use the file names (which Chet agreed to) then this shouldn't be needed. Using these to generate file names with OASIS naming conventions breaks relative links in the multi-part specifications.

**Comment by berezovskyi** [comment]
Oh, I see! Forgot about that requirement already. If @ndjc confirms, I can remove them.

**Comment by ndjc** [comment]
As far as I know, we now do have agreement to use relative path names, so we do not need these variables.

**Comment by berezovskyi** [comment]
What about `oslcVersion: "3.0"`?
