### ISSUE TITLE
Part 7 Vocab is missing a conformance table

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#104]
![image](https://user-images.githubusercontent.com/64734/62787048-2514fe80-bac4-11e9-88ea-4aa6efff1ceb.png)

I assume we don't need it in that part but then we should do something with the warning.

**Comment by ndjc** [comment]
If a document does not need a conformance table, it can leave out the conformance section and set the variable conf.noConformanceTable = true.

**Comment by berezovskyi** [comment]
@jamsden if you confirm a conformance table is not needed for the vocab, I can make the change.

**Comment by jamsden** [comment]
Confirm, the vocabulary is covered as a conformance item in the spec.

**Comment by berezovskyi** [comment]
Just pushed https://github.com/oslc-op/oslc-specs/pull/103/commits/66828a6348ff55e177086c962284e63ff7d87fca but it did not solve the issue, see https://github.com/oasis-tcs/tab-respec/issues/8
