### ISSUE TITLE
remove the Change History appendix

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#107]
Chet approved the move

**Comment by ndjc** [comment]
Can someone explain this a bit more? Why are we removing the history? From which docs? Back to or from some point?

There's not enough info in this issue.

**Comment by berezovskyi** [comment]
@jamsden could you please take this one? I was just CCed on Chet’s sign-off on this but you have the context.

--
/Andrew
(from phone)

12 aug. 2019 kl. 23:31 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


Can someone explain this a bit more? Why are we removing the history? From which docs? Back to or from some point?

There's not enough info in this issue.

**Comment by jamsden** [comment]
The change history appendix has never been particularly useful. It did explain significant changes the document status and revision and was required by OASIS for committee specifications. A change log also had to be generated and published with each revision. Chet has agreed that the former is better handled by commit messages, and the latter is already available as needed from Git. He has agreed that we no longer need to include this section in OP documents.

Let's hold off on removing them from all documents except the CM specs and get that one to PS status to see what OASIS will ultimately accept.

**Comment by berezovskyi** [comment]
Thanks for the explanation, Jim!

I agree that the table was not very useful but I am not sure that anyone will go through hundreds of Git commits in search of some minute changes. For example, we just started keeping a CHANGELOG in Lyo: https://github.com/eclipse/lyo.core/blob/master/CHANGELOG.md (started in 2.4.0 with this: https://forum.open-services.net/t/lyo-2-4-0-release-notes/161/2)

So, I would be very much in favour of keeping a clear changelog for people with OSLC 2 compliant servers to find out what changed and what's new.

Let's proceed without the section in the first CM PSD as suggested.

**Comment by jamsden** [comment]
I'm inclined to leave them and just note any significant change that server implementers might need to be aware of. So closing this with no further action.
