### ISSUE TITLE
wgPatentURI is obsolete

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#109]
The conf variable `wgPatentURI`  is obsolete, and should be removed from all specs.

**Comment by berezovskyi** [comment]
Will fix on Core and RM. @jamsden could you please remove from CM?

--
/Andrew
(from phone)

12 aug. 2019 kl. 23:30 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


The conf variable wgPatentURI is obsolete, and should be removed from all specs.

**Comment by berezovskyi** [comment]
Fixed in #113.
