### ISSUE TITLE
Use permalinks inside new specs

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#11]
I suggest to use [PURLs](https://www.wikiwand.com/en/Persistent_uniform_resource_locator) to point to external links from our specs.

The original PURL service is now run by the Internet Archive: https://archive.org/services/purl/

I have registered a sample URL: http://purl.org/oslc/core

Before PURL was handed over to the IA, a few companies proposed a similar service under W3C: https://w3id.org/

PURL is OSS, so OASIS might want to run its own instance of it.

**Comment by berezovskyi** [comment]
@jamsden would you like to check with Chet about that?

**Comment by jamsden** [comment]
This should be unnecessary for relative links between closely related documents in the same multi-part specifications. For links to other related OASIS specifications, the convention has been to use docs.oasis-open.org latest URL which OASIS maintains. 

For links to old open-services.net documents, we need to get the redirects setup.

**Comment by berezovskyi** [comment]
I fully agree on the relative links.

The suggestion was to set up PURLs for the absolute links in the new specs.

For the old documents, we can set up non-PURL redirects directly on our server for any links that are reported broken in #10.

**Comment by berezovskyi** [comment]
Will use open-services.net, see https://github.com/oslc-op/oslc-specs/issues/66 and https://github.com/oslc-op/oslc-specs/wiki/Guidelines-for-Defining-URIs
