### ISSUE TITLE
Link validity discovery

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#117]
IBM Engineering Lifecycle Management has a capability to record whether links from a source version artifact to a target version artifact are valid or invalid. There is a requirement that, for reporting purposes, the reporting tool can determine from the artifact's resource shape, whether an OSLC property representing a link supports link validity or not.

If such a capability is of wider interest among OSLC stakeholders, then it would be better to use a predicate in the oslc namespace on an OSLC property. Otherwise, a predicate in some private namespace will be used and will not be part of any OSLC specification.

**Comment by jamsden** [comment]
This is something we should discuss. OSLC core does have some text regarding traceability and impact type, and discovering support for link validity would seem closely related.

David, could you put a specific proposal on the oslc-op mailing list to introduce the discussion?

**Comment by berezovskyi** [comment]
David, do you have a description of such a capability you can post here? The proposal is pertinent and is something I considered doing by monitoring TRS changes on the resources I link to (their servers to be more precise).

Also, what is the definition of “valid”? 2xx code returned, shape validation pass, or some CfgM specific value checks are satisfied?

--
/Andrew
(from phone)

15 aug. 2019 kl. 17:16 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


This is something we should discuss. OSLC core does have some text regarding traceability and impact type, and discovering support for link validity would seem closely related.

David, could you put a specific proposal on the oslc-op mailing list to introduce the discussion?

**Comment by berezovskyi** [comment]
@DavidJHoney I still fail to understand the core idea behind this. An extended description would be essential for us to proceed.

**Comment by DavidJHoney** [comment]
I will try to add some more details before the end of next week. However, there is a chance that won’t get done and then it will have to wait until October.

**Comment by berezovskyi** [comment]
Please reopen when you are ready.
