### ISSUE TITLE
PROMCODE overlap?

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#12]
I briefly checked the [Chapter 3](https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/WorkingDrafts/promcode-interface-v1.0-wd01_Chapter3.docx?rev=295&sc=1) of the latest spec draft and it seems that certain portions of their spec overlap with other OSLC domains:

![image](https://user-images.githubusercontent.com/64734/51332509-27f2c800-1a7c-11e9-9c1b-b2728498ee1f.png)

For example ([CM vocab spec](http://docs.oasis-open.org/oslc-domains/cm/v3.0/cs02/part2-change-mgt-vocab/cm-v3.0-cs02-part2-change-mgt-vocab.html#introduction)):

- `oslc_prom:WorkItem` vs `oslc_cm:Task`
- `oslc_prom:Issue` vs `oslc_cm:Defect`

and others.

What am I missing?

**Comment by jamsden** [comment]
That could be argued. But its not clear WorkItem for example is a kind of 
ChangeRequest. That is certainly something that could be brought up in a 
public review and would be easy to fix.


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by berezovskyi** [comment]
@sarabura can't assign you through the UI :)

**Comment by berezovskyi** [comment]
not getting any replies from them
