### ISSUE TITLE
TRS spec needs to be clearer about the semantics of the cutoff event

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#19]
Currently, there is scope for misinterpreting the spec about the semantics of the cutoff event. In some sections, it suggests that the TRS consists of the base plus events in the change log. This implies that the event in the change log referenced by the base's cutoff event is an active event that should be processed. However, the description of the base cutoff event later says that only events _after_ this event in the change log are active. The specification should be more explicit about this - an example would help to reinforce the intended semantics.

**Comment by berezovskyi** [comment]
I assume the latter is correct?

Also, added a 'nota-bene' label that you can use so that we will know not to reply.

**Comment by ndjc** [comment]
**PROPOSED**: The spec wording has been updated, but nonetheless Nick should add more examples.

**Comment by ndjc** [comment]
I did not add examples. If this is still required, a new issue should be opened.
