### ISSUE TITLE
Defect in OSLC Core 3.0 Discovery, service provider dcterms:publisher

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#21]
In Core 3.0 Discovery, the oslc:ServiceProvider shape includes dcterms:publisher.
This used to be oslc:publisher and this is what existing apps have been using.
The range is defined as oslc:Publisher. So it looks like an unintentional change that breaks compatibility with OSLC 2.0.

**Comment by jamsden** [comment]
OSLC Core 2.0 vocabulary does not define Property oslc:publisher, only class oslc:Publisher. The HTML tables in the Core 2.0 specifications (which were used to create the 3.0 resource shapes files) references ServiceProviderCatalog and ServiceProvider dcterms:publisher property with range oslc:Publisher. So Core 3.0 is compatible with the Core 2.0 specification.

I just checked RTC 6.0.6.1 ServiceProviderCatalog and it uses dcterms:publisher for the property and its object is an oslc:Publisher.

**Comment by DavidJHoney** [comment]
However, I see RTC, DNG, QM, and GCM 6.0.6 all using oslc:publisher and not dcterms:publisher.
I verified this using SPARQL in LQE that indexed artifacts from those applications.
Perhaps this was from OSLC 1.0?

**Comment by berezovskyi** [comment]
Nick, we can bring `oslc:publisher` back and mark it archaic as per Nick's suggestion: https://github.com/oslc-op/oslc-specs/issues/53#issuecomment-502743002 just to ensure no compat is broken.

**Comment by jamsden** [comment]
This was not included in Core PSD04 vocabulary.

**Comment by jamsden** [comment]
I added oslc:publisher to core vocabulary, marked as   vs:term_status "archaic" ;

But I did not add it to any of the shapes.
