### ISSUE TITLE
oslc:range in an oslc:Property

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#22]
The shape for oslc:Property defines oslc:range as follows:

oslc:range | One-or-many | true | Resource | Reference | rdfs:Class | For object properties, specifies what the target resource type is expected to be, but that is not necessarily the case.

Should we consider making the cardinality Zero-or-many?
The semantics would be that the target type is undefined.
If we decide to keep it as is, how does a shape define a property with an undefined target type?
For example, should it oslc:range oslc:Resource?
The specification should be more explicit about how to handle this case.

The wording could be improved to cover the case where two or more oslc:range values are specified. Current usage by Rational DNG and QM are that the referenced artifact can be _any_ of the specified types.

**Comment by berezovskyi** [comment]
> The semantics would be that the target type is undefined.

The semantics would be that the target type is `oslc:AnyResource`.

**Comment by berezovskyi** [comment]
I think it would be acceptable

**Comment by berezovskyi** [comment]
> The wording could be improved to cover the case where two or more oslc:range values are specified. Current usage by Rational DNG and QM are that the referenced artifact can be any of the specified types.

That would be a very important update under https://oslc-op.github.io/oslc-specs/specs/core/resource-shape.html#h2_shape-resource-shapes! Please do it 🙏

**Comment by ndjc** [comment]
We agreed to allow multiple values of oslc:range, with one possible value being oslc:Any to indicate an escape to allow any resource type. (Note: not oslc:AnyResource. That is an enum value for the representation.)
Zero values should be equivalent to oslc:Any.
