### ISSUE TITLE
CM spec does not refer to the Turtle files

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#220]
I zipped up the Turtle files with the PSD given they are now normative.

Paul said:

> There are also two .ttl files and an image file included in the publication directory. These files have not been modified. The specification files do not refer to the .ttl files.

We shall ensure the vocab part references them directly and not just through the open-services.net URI.

**Comment by jamsden** [comment]
Resolved by https://github.com/oslc-op/oslc-specs/pull/360
