### ISSUE TITLE
Solicit statements of use for Change Management 3.0

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#23]
The following email can be sent to the oslc-domains mailing list, and to known implementers of CM that are OASIS Members:

The OSLC Change Management 3.0 Committee Specification, revision 02 represents a milestone in the standardization process for open-services.net specifications. This revision incorporates the insight gained from many implementations, integrations with other lifecycle management tools, and user experience, while maintaining compatibility with OSLC Change Management Specification Version 2.0 (http://open-services.net/bin/view/Main/CmSpecificationV2) developed by open-services.net. Implementations of this specification are therefore applicable for Statements of Use of Change Management 3.0.

The OSLC Domains TC is ready to accept Statements of Use from implementers. This is an essential part of the OASIS standardization process and will enable us to progress to OASIS Standard. Please see Section 2.8.1 of the TC process for more information. In summary:

> "Statement of Use", with respect to a Committee Specification or Project Specification, is a written statement that a party has successfully used or implemented that specification in accordance with all or some of its conformance clauses, identifying those clauses that apply, and stating whether its use included the interoperation of multiple independent implementations. The Statement of Use must be made to a specific version of the Specification and must include the Specification's approval date. The party may be an OASIS Member or a non-member. In case of a non-member, the Statement of Use must be submitted via the Technical Committee's or Project Governing Board's comment facility. A TC or PGB may require a Statement of Use to include hyperlinks to documents, files or demonstration transcripts that enable the committee's members to evaluate the implementation or usage. A Statement of Use submitted to the TC or PGB must be approved by TC Resolution or PGB action as an acceptable Statement of Use with respect to the Specification. A party can only issue one Statement of Use for a given specification. When issued by an OASIS Organizational Member, a Statement of Use must be endorsed by the Organizational Member's Primary Representative.

Statements of Use must be endorsed by the OASIS Organizational Member's Primary Representative. Submitters just need to notify the Technical Committee, by submitting their 'Statement of Use' to the oslc-domains-comment list (oslc-domains-comment@lists.oasis-open.org). A typical statement of use could be:

<insert name / org here> has successfully implemented the OASIS Change Management Specification, Version 3.0, Committee Specification 02 (http://docs.oasis-open.org/oslc-domains/cm/v3.0/cs02/part1-change-mgt/cm-v3.0-cs02-part1-change-mgt.html) dated 24 August 2018, in accordance with the conformance clauses defined in Section 5 "Conformance" of the specification. This use of the specification includes interoperation with other similar independent implementations, as well as integration with tools supporting other OSLC domain specifications.

**Comment by berezovskyi** [comment]
Do we need them for PS or only for COS? If we need them already for the PS, please change the milestone accordingly.

**Comment by chet-ensign** [comment]
You only need SoUs when you vote to proceed to Candidate OASIS Standard. In fact, you need the PS first because the SoU must include the PS title, version number, and approval date.

**Comment by berezovskyi** [comment]
Perfect, thanks!
