### ISSUE TITLE
RM vocab check warnings

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#231]
I get the following warnings in the build:

```
Checked vocabulary http://open-services.net/ns/rm# from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/rm/requirements-management-vocab.ttl, with 3 issues (0 info, 3 warnings, 0 errors)
   While examining ontology http://open-services.net/ns/rm#:
      Warning on https://github.com/oslc-op/oslc-specs/blob/master/specs/blob/master/rm/requirements-management-vocab.ttl: This resource is not fetchable. (bad value 404)
   While examining vocabulary term http://open-services.net/ns/rm#Requirement:
      Warning on http://open-services.net/ns/core#hasBasicShape: This property is unexpected. (bad value http://open-services.net/ns/rm#requirementShape)
   While examining vocabulary term http://open-services.net/ns/rm#RequirementCollection:
      Warning on http://open-services.net/ns/core#hasBasicShape: This property is unexpected. (bad value http://open-services-net/shapes/rm#requirementCollectionShape)
```

@jadelkhoury, @ndjc could you please check and see if this needs fixing?

**Comment by berezovskyi** [comment]
@jadelkhoury please remove from the PSD02 milestone if you think this need not be fixed now.

**Comment by ndjc** [comment]
There's no such property as oslc:hasBasicShape, so those two warnings are correct. Presumably RM is trying to use a predicate that is sort of the inverse of oslc:describes on a shape, but Core never defined such a thing.

**Comment by berezovskyi** [comment]
Thanks Nick. Jad, I think we should fix it as part of the PSD prep.

**Comment by ndjc** [comment]
And the URI that ShapeChecker cannot read is indeed a bad URI (https://github.com/oslc-op/oslc-specs/blob/master/specs/blob/master/rm/requirements-management-vocab.ttl), with two occurrences of blob/master in it. Even if corrected, I thought we were going to use raw.githubusercontent.com for raw source references, to get the true unrendered source.
