### ISSUE TITLE
Publish the first RM PSD

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#237]
@jadelkhoury @jamsden I think we should publish the PSD for the RM spec once oslc-op/oslc-admin#25 is closed. I took some effort to whip it into the OP shape and I think the spec look good overall, esp. after the https://github.com/oslc-op/oslc-specs/pull/119 is complete.

See https://github.com/oslc-op/oslc-specs/milestone/4 for the scope of work

**Comment by jadelkhoury** [comment]
Status: I managed to update the publication date to 1 October. 

Besides that, I could not find any of the other changes in the html pages. Even after I ran `python -m http.server 8080`, I still can't find this code.

Comparing files requirements-management-spec.html and REQUIREMENTS-MANAGEMENT-SPEC-NEW.HTML
***** requirements-management-spec.html
  420:      
  421:        <a href="https://www.oasis-open.org/" target="_blank"><img width="50%" src="//docs.oasis-open-projects.org/templates/logo
  422:  /open-projects-logo.png" alt="OASIS Open Projects" border="0"></a>
  423:        </p><hr>
***** REQUIREMENTS-MANAGEMENT-SPEC-NEW.HTML
  420:      
  421:        <a href="https://www.oasis-open.org/" target="_blank"><img width="50%" src="https://docs.oasis-open-projects.org/template
  422:  s/logo/open-projects-logo.png" alt="OASIS Open Projects" border="0"></a>
  423:        </p><hr>
*****

***** requirements-management-spec.html
  433:      <span property="dcterms:issued" datatype="xsd:dateTime" content="2019-09-08T22:00:00.000Z"><time class="dt-published" datet
  434:  ime="2019-09-09">09 September 2019</time></span>
  435:      
***** REQUIREMENTS-MANAGEMENT-SPEC-NEW.HTML
  433:      <span property="dcterms:issued" datatype="xsd:dateTime" content="2019-09-08T22:00:00.000Z"><time class="dt-published" datet
  434:  ime="2019-09-09">01 October 2019</time></span>
  435:      
*****

***** requirements-management-spec.html
  606:      Edited by Mark Schulte and Jad El-khoury.
  607:      09 September 2019.
  608:      OASIS  Project Specification Draft 02.
***** REQUIREMENTS-MANAGEMENT-SPEC-NEW.HTML
  606:      Edited by Mark Schulte and Jad El-khoury.
  607:      01 October 2019.
  608:      OASIS  Project Specification Draft 02.
*****


Comparing files requirements-management-vocab.html and REQUIREMENTS-MANAGEMENT-VOCAB-NEW.HTML
***** requirements-management-vocab.html
  416:      
  417:        <a href="https://www.oasis-open.org/" target="_blank"><img width="50%" src="//docs.oasis-open-projects.org/templates/logo
  418:  /open-projects-logo.png" alt="OASIS Open Projects" border="0"></a>
  419:        </p><hr>
***** REQUIREMENTS-MANAGEMENT-VOCAB-NEW.HTML
  416:      
  417:        <a href="https://www.oasis-open.org/" target="_blank"><img width="50%" src="https://docs.oasis-open-projects.org/template
  418:  s/logo/open-projects-logo.png" alt="OASIS Open Projects" border="0"></a>
  419:        </p><hr>
*****

***** requirements-management-vocab.html
  429:      <span property="dcterms:issued" datatype="xsd:dateTime" content="2019-09-08T22:00:00.000Z"><time class="dt-published" datet
  430:  ime="2019-09-09">09 September 2019</time></span>
  431:      
***** REQUIREMENTS-MANAGEMENT-VOCAB-NEW.HTML
  429:      <span property="dcterms:issued" datatype="xsd:dateTime" content="2019-09-08T22:00:00.000Z"><time class="dt-published" datet
  430:  ime="2019-09-09">01 October 2019</time></span>
  431:      
*****

***** requirements-management-vocab.html
  597:      Edited by Mark Schulte and Jad El-khoury.
  598:      09 September 2019.
  599:      OASIS  Project Specification Draft 02.
***** REQUIREMENTS-MANAGEMENT-VOCAB-NEW.HTML
  597:      Edited by Mark Schulte and Jad El-khoury.
  598:      01 October 2019.
  599:      OASIS  Project Specification Draft 02.
*****

**Comment by jadelkhoury** [comment]
I updated to respec 2.1.12 on the branch https://github.com/oslc-op/oslc-specs/tree/b-rm-psd02.
This solves most request changes by OASIS, but 1 remains. Plus, I now get 4 new(?) respec errors.

1. There was also a demand to for the URLs of the "Additional components" to be relative.

I tried "./requirements-management-vocab.html" & "./requirements-management-vocab.html".
Now, both alternatives lead me to the page "https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/psd02/requirements-management-vocab.html", with the error message that the page does not exist.

2. When viewing the vocab.html page, I get the following 4 errors:
* A conformance paragraph or table is required for your type of document.

* Error including URI=./requirements-management-vocab.ttl: error (NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/psd02/requirements-management-vocab.ttl'.)

* Error including URI=./requirements-management-shapes.ttl#Requirement: error (NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/psd02/requirements-management-shapes.ttl'.)

* Error including URI=./requirements-management-shapes.ttl#RequirementCollection: error (NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/psd02/requirements-management-shapes.ttl'.)
