### ISSUE TITLE
Republish all OSLC Committee Specifications as oslc-op Project Specifications

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#238]
This will require style, template URL and updates to get the specifications to render properly using the updated ReSpec. 

For the domains specifications, see: https://github.com/oslc-op/oslc-specs/wiki/OSLC-Domains-Working-Documents

There will be a separate issue for the core specs since they need to go through another public review.

**Core:**

- [x] 🚧 Core (Jim)
- [ ] TRS (Nick)
- [x] Query

**Domains (prio):**

- [x] 🚀  **RM (Jad, WIP)**
- [x] ✅ CM
- [x] 🚧 QM (Andrew)
- [ ] CfgM

**Domains (rest):**

- [ ] AM
- [ ] EMS
- [ ] Automation
- [ ] Access (ILDP)
- [ ] Asset
- [ ] PerfMon
- [ ] Recon

**Comment by berezovskyi** [comment]
See https://hackmd.io/GBxx8iRLS3Sf-VvZM2z1Dw?both (bottom part) and https://docs.google.com/spreadsheets/d/1phBv2PHh14VSZboBpmq4KuWn8hw4wZr2qHGVB2W6PIY/edit?usp=drive_open&ouid=117532123105813824723 for the current status
