### ISSUE TITLE
Produce a TRS 2.0 vocab

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#241]
As part of my work on https://github.com/oslc-op/website/issues/265, I need a TRS 2.0 vocab file.

The earliest commit of the TRS vocab goes back to https://github.com/oslc-op/oslc-specs/commit/b7b3d9387d0b4290ddae7723fa426cdb65f9dd12#diff-3201e17e8e9fbe803a4303b7a638971f that Jim made in SNV on 20 Jul 2016. Unfortunately, it does not correspond to the 2.0 spec and the vocab cannot be found in the archive as it was never published.

If you agree, I will produce a TRS spec vocab myself out of the existing one by removing the ILDP and TRS Patch stuff from the current vocab and cross-check it with the old ones.

**Comment by berezovskyi** [comment]
cc @jamsden @ndjc

**Comment by berezovskyi** [comment]
@ndjc shall we close it because it is going to be handled in oslc-op/website#265 or shall we approach this separately? I no longer have an urgent need for the vocab.

**Comment by ndjc** [comment]
Will not fix at this point.
