### ISSUE TITLE
Decide on a canonical RM 2.0 URL

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#242]
The latest modified URI is https://archive.open-services.net/wiki/requirements-management/OSLC-Requirements-Management-Specification-version-2.0/index.html

However, the spec has been edited on https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html and was likely transferred to the new location at the end.

The "new" link renders the HTML tables poorly and does not seem to add much in terms of the content. Can we agree on using the old wiki link as the canonical one?

@img have there been any content changes to the spec between the 21 Sep 2012 and 10 Oct 2012?

@jadelkhoury with version of the spec was used as the basis for the RM 2.1 draft?

**Comment by jadelkhoury** [comment]
https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html seems to be the original, from which the other was copied. and it looks better.

So, I'd vote for https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html

**Comment by jadelkhoury** [comment]
we are currently pointing to http://open-services.net/bin/view/Main/RmSpecificationV2 which is fine. 
So, won't fix.
