### ISSUE TITLE
Explain use of multiple OSLC Query prefixes

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#243]
See https://jazz.net/forum/questions/143241/rrc-v405-and-oslc-query/143284

https://archive.open-services.net/bin/view/Main/OSLCCoreSpecQuery#Prefixed_Names does not have this explanation.

**Comment by DavidJHoney** [comment]
I think the query spec covers this usage by referencing OSLC Core 3.0. So if this remains an issue, I think it's one for Core rather than Query.

**Comment by berezovskyi** [comment]
Reassign to the main spec, @jamsden please consider if it can be addressed in the PS

**Comment by jamsden** [comment]
I can find no query examples that use oslc.prefix with multiple, comma separated prefix=<uri> values. So I'm not sure this is even correct even though it is in Core 3.0. David, Nick, do you think this is supported or is Core 3.0 incorrect and multiple ?oslc.prefix query parameters are required, one for each prefix being defined? I would actually prefer that I think.

**Comment by berezovskyi** [comment]
@jamsden we are talking about a repeated URI query parameter with the key 'oslc.prefix', see https://jazz.net/forum/questions/143241/rrc-v405-and-oslc-query/143284

**Comment by jamsden** [comment]
It appears the repeated oslc.prefix query parameter may be the required syntax. I can find no examples of multiple oslc.prefix query parameters, with or without commas, so I don't know what was intended for OSLC core 2.0.

**Comment by berezovskyi** [comment]
What I meant initially is that while it works with IBM products, the spec does not mention at all how to specify multiple prefixes.

**Comment by jamsden** [comment]
Right, and I don't know what the right answer should be. David would need to weigh in on what was implemented. That would at least show the intent. There appears to be no clarifying documentation.

**Comment by DavidJHoney** [comment]
oslc.prefix is described in 4.7 Selective Properties in https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/oslc-core.html. It is a single parameter whose value is a comma separated list of entries.

**Comment by jamsden** [comment]
Yes, but is that consistent with OSLC 2.0? This might have been something I added to 3.0 thinking it was supported in 2.0. But I can't find any formal specification of oslc.prefix in 2.0 that indicates a comma-separated list is supported, at least some of the jazz.net apps don't seem to support it, and I can't find any examples that use it.

**Comment by berezovskyi** [comment]
@DavidJHoney the referenced Jazz forum question did exactly what you said should be the new OSLC 3 behaviour and got a reply to use repeated URI query parameters instead. Do you suggest RRC team shall change their implementation?

I would suggest to at least add that OSLC Server

> MAY allow multiple `oslc.prefix` URI query parameters for backwards compatibility, defining a single prefix at a time.

This would clearly explain the behaviour exhibited by RRC and avoid breaking compatibility. I see no technical reason to drop one in favour of another. In addition, most web frameworks can convert multiple URI query params into a List, so you don't have to even split a string in the application code.

**Comment by DavidJHoney** [comment]
The syntax of oslc.prefix in OSLC 2.0 at https://archive.open-services.net/bin/view/Main/OslcCoreSpecification.html also uses comma.

Neither OSLC  Core 2.0 nor Core 3.0 say anything about multiple oslc.prefix parameter values. While some implementations might support it, this doesn't seem safe in general. For example, an implementation using ServletRequest.getParameter(String name) will only get one parameter value. Since the specification does not define the behavior here, such an implementation would be conformant. There is no guarantee that specifying multiple oslc.prefix parameters will be treated transparently to a consuming server as the same as one parameter with comma separated values.

On that basis, the if RRC is relying on support for multiple oslc.prefix parameters, that seems unsafe in both OSLC 2.0 and 3.0, and I suggest they construct a single comma-separated value instead.

**Comment by jamsden** [comment]
Ok, I missed that in core (I was searching the query document). So I think we're good. 

At least one example, proven against an implementation, would be good. I think I had problems with this w/ DNG.

**Comment by jamsden** [comment]
We agreed on today's telecon that there isn't much we can say in general about how clients and servers should implement multi-valued query parameters. Common practice would seem to indicate that either comma separated values on a single query parameter, or multiple instances of the same query parameter are ok. 

However, we have defined the syntax for all OSLC query parameters (including prefix) and it is reasonable to expect servers to implement that, and clients to use it. If a client attempts to use multiple prefix parameters a server should be free to return Bad Request. A server may also support multiple prefix parameters, even though the OSLC spec does not cover this. 

However, a server that does not support prefix with comma separated values would have a bug, even through clients could work around it with multiple prefix parameters.
