### ISSUE TITLE
QM p.conformance paragraphs are not assigned c CC number

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#247]
```html
<p class=‘conformance’>This specification is based on [[!OSLCCore3]]. OSLC QM
servers MUST be compliant with both the core specification,  MUST follow all
the mandatory requirements in the normative sections of this specification, and
SHOULD follow all the guidelines and recommendations in both these
specifications.</p>
```

![image](https://user-images.githubusercontent.com/64734/65078877-40660a00-d99e-11e9-9cf3-ce19a2f4a629.png)

**Comment by berezovskyi** [comment]
@ndjc is this a bug in ReSpec? If not, how whall I fix it in the spec source?

@jamsden I totally missed the requirements on conf clauses? Do we have to mark those 4 clauses before the table with the CC numbers?

**Comment by ndjc** [comment]
You have curly quotes around the ‘conformance’ class name - ReSpec and/or the browser I use only seem to support straight quotes 'conformance'.
