### ISSUE TITLE
Query syntax shall be fixed

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#254]
While fixing #252, I saw

> OSLC query capabilities SHOULD support the OSLC Core Query Syntax and MAY use other query syntax

I think SHOULD shall be changed to MUST. We have an OSLC Query parser in Lyo, it requires a custom ANTLR gramar and a generated parser. It would be rather imprudent to ever allow implementations to use a non-standard syntax that will require yet another parser.

**Comment by berezovskyi** [comment]
@jamsden @ndjc

**Comment by berezovskyi** [comment]
Clarification: extensions shall be allowed but the things Query spec defines may not be overridden by the implementors.

**Comment by ndjc** [comment]
QM 2.0 does state:

> OSLC service providers MUST provide query capabilities to enable clients to query for resources
>OSLC query capabilities MUST support the OSLC Core Query Syntax and MAY use other query syntax

I see little reason to weaken those constraints in 2.1.

**Comment by jamsden** [comment]
The intent was that OSLC servers should support OSLC Query and may support other query languages, not that the OSLC query syntax was open (other than the optional parts).

**Comment by berezovskyi** [comment]
So, you mean a SHOULD/MAY combination would not allow non-OSLC-Query queries to be submitted to the server in the `oslc.where` query parameter, for example?

**Comment by jamsden** [comment]
Right. if servers support OSLC Query, then the follow OSLC Query conformance clauses. Servers may also provide other query facilities such as SPARQL, SQL, etc.

**Comment by berezovskyi** [comment]
Okay, time for a rant: I agree that devs should be free to offer SPARQL or LDF over OSLC  Query.

At the same time, I am not sure what value do end customers get (lose). Most of the products I have seen (except IBM, of course, which implements most of the specs nearly completely) either skip should/may features or implement them in incompatible ways.

Do customers expect Query support to work across many QM domain products? I am not sure, but I think yes. Especially if they rely on Query to produce traceability reports for their digital thread efforts. Axel, Jad, please correct/confirm my thoughts. Cc @axelreichwein @jadelkhoury

If you disagree, I think it’s time for us to think of declaring OSLC Profiles. To say: look, here are five products and you are not getting them to integrate well despite your persistent efforts and a fair amount of blood and tears. It’s not because OSLC is totally useless but because 3 of those products implement OSLC QM 2.1 Basic Profile only. Will also be a good marketing incentive for the vendors to implement SHOULDs.

--
/Andrew
(from phone)

23 sep. 2019 kl. 21:47 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


Right. if servers support OSLC Query, then the follow OSLC Query conformance clauses. Servers may also provide other query facilities such as SPARQL, SQL, etc.

**Comment by ndjc** [comment]
The discussion of additional query syntaxes that QM or other domains might or might not support is interesting, but irrelevant. Yes, OSLC Core itself simply presents the OSLC Core Query syntax as something domains MAY use - but as I already quoted, QM 2.0 overrode this - as it was entitled to so - and says that QM implementations MUST allow query, and MUST allow such queries to use OSLC Core query syntax. That's all the spec need say - that does not prohibit support for other syntaxes.
Weakening the QM 3.0 support for query syntax to a MAY for OSLC Core query syntax invites servers to be incompatible with 2.0 clients, for no good reason.
The reversion of this change was correct.

**Comment by ndjc** [comment]
And yes, we need to expect queries to work across providers in at least several classic cases - for example, IBM products use OSLC queries to discover incoming links in some scenarios. Non-portable queries would prevent link discovery in the presence of divergent providers.

**Comment by berezovskyi** [comment]
Thanks Nick. @axelreichwein @jadelkhoury @jamsden awaiting your reply to make sure we have a consensus before I close the issue.

**Comment by jamsden** [comment]
Ok to close...

**Comment by jadelkhoury** [comment]
ok to close.
