### ISSUE TITLE
Ensure QM 2.1 compat with QM 1.0

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#256]
Removed section: https://archive.open-services.net/bin/view/Main/QmSpecificationV2.html#Version_Compatibility_with_1_0_S

I think the best way forward is to add a few base conformance clauses:

- OSLC QM servers MAY use `application/x-oslc-qm-*` media types in responses for compatibility with [QM 1.0 systems](https://archive.open-services.net/bin/view/Main/QmRestApiV1.html) [QM10].

This also means closing #92 as wontfix due to QM 1.0 declaring it a MUST: https://archive.open-services.net/bin/view/Main/QmRestApiV1.html#Get_a_collection_of_QM_resources

**Comment by berezovskyi** [comment]
@jamsden @ndjc waiting for your opinion

**Comment by ndjc** [comment]
I agree with the proposal.

**Comment by jamsden** [comment]
I also agree with the proposal. This is a good general approach to compatibility.
