### ISSUE TITLE
Update PSD references to point to the latest revisions

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#257]
Started from a discussion in https://github.com/oslc-op/oslc-specs/pull/246

Awaiting https://github.com/oasis-tcs/tab-respec/issues/21

**Comment by jamsden** [comment]
What specifically needs to be done in Core?

**Comment by berezovskyi** [comment]
Nothing. It should be an issue for the domain specs to point to the Core spec from OP.

--
/Andrew
(from phone)

On 12 Mar 2020, at 18:52, Jim Amsden <notifications@github.com<mailto:notifications@github.com>> wrote:


What specifically needs to be done in Core?

**Comment by berezovskyi** [comment]
Updated the checklist under https://github.com/oslc-op/oslc-specs/wiki/EPIC-checklist to have a new item:

> Update references to obsolete PSDs to point to the latest revisions. See https://open-services.net/specifications/ for a list of obsolete publications.
