### ISSUE TITLE
Add some inverse labels to QM vocabulary

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#261]
For reporting across RM and QM domains, oslc:inverseLabel values on properties are useful. In particular, the following are suggested:
```

oslc_qm:affectedByChangeRequest         oslc:inverseLabel  "Affects Test Case Result" .
oslc_qm:blockedByChangeRequest          oslc:inverseLabel  "Blocks Test Case Execution Record" .
oslc_qm:executesTestScript              oslc:inverseLabel  "Executed By" .
oslc_qm:relatedChangeRequest            oslc:inverseLabel  "Related Test Artifact" .
oslc_qm:reportsOnTestCase               oslc:inverseLabel  "Reported By" .
oslc_qm:reportsOnTestPlan               oslc:inverseLabel  "Reported By" .
oslc_qm:runsTestCase                    oslc:inverseLabel  "Run By" .
oslc_qm:testsChangeRequest              oslc:inverseLabel  "Tested By Test Case" .
oslc_qm:usesTestCase                    oslc:inverseLabel  "Used By" .
oslc_qm:usesTestScript                  oslc:inverseLabel  "Used By" .
oslc_qm:validatesRequirement            oslc:inverseLabel  "Validated By" .
oslc_qm:validatesRequirementCollection  oslc:inverseLabel  "Validated By" .

```

**Comment by ndjc** [comment]
This change was requested by the IBM/Persistent development team, and would be used by the reporting tools to offer the right set of link types when building reports with QM artifacts as the link targets.

**Comment by berezovskyi** [comment]
What’s an inverse label?

**Comment by jamsden** [comment]
Its a suggestion on a shape property that is a reference as to what the name of the reference in the other direction might be. Its useful for reporting tools, and for tools that query for incoming links. Instead of hard-coding the link from the querying tool's perspective, it can discover what the tool owning the link thinks the name from the other direction should be.
