### ISSUE TITLE
ShapeChecker: incorrect list of vocabulary terms seen with the --verbose option 

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#262]
With more complex vocabulary terms, an incorrect list of such terms can be shown by ShapeChecker when the --verbose flag is used.

The name as shown is the local name of the term resource. If the term URI is structured, the local name is not always unique, or useful. The entire URI should be shown.

**Comment by ndjc** [comment]
Closed via pr 263.

**Comment by berezovskyi** [comment]
@ndjc for the future: https://help.github.com/en/articles/closing-issues-using-keywords

"Closes #262" in the PR would have done the trick.
