### ISSUE TITLE
Reorganise the repo layout

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#27]
Let's do as much work as we can before the OP is established and prepare the repo for merging the Domains in.

I am planning to use [git branch filter](https://stackoverflow.com/questions/4042816/how-can-i-rewrite-history-so-that-all-files-except-the-ones-i-already-moved-ar) to move all the stuff inside the oslc-domains into the `/domains` directory and [merge it into this repo](https://stackoverflow.com/a/10548919/464590).

Let's reorganise the folders here to be ready for that move.

**Comment by berezovskyi** [comment]
cc @graybachelor as a workaround :)

**Comment by jamsden** [comment]
This is beyond what I would have time (or git skills) to do. I can propose what should be moved where and will do that in this issue.

**Comment by jamsden** [comment]
Here's my proposed organization. The easiest was for me to create this was to just copy everything into a new folder. You can diff this with the existing folders to figure out what needs to be moved.

[oslc-op (draft).zip](https://github.com/oasis-tcs/oslc-core/files/3139827/oslc-op.draft.zip)

**Comment by berezovskyi** [comment]
Thanks Jim,

My suggestion would be to keep core specs separate from the domains specs. I think it makes more sense and will be easier from the tech side to do.

I would also suggest (re)moving as much of the non-spec stuff out of the repo. I saw some Word templates in there etc.

--
/Andrew
(from phone)



On Thu, May 2, 2019 at 10:25 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's my proposed organization. The easiest was for me to create this was to just copy everything into a new folder. You can diff this with the existing folders to figure out what needs to be moved.

oslc-op (draft).zip<https://github.com/oasis-tcs/oslc-core/files/3139827/oslc-op.draft.zip>

**Comment by jamsden** [comment]
Each spec is in a separate folder under specs, including core, trs, query, 
config management, and all the domain specs. This keeps them all organized 
in a single place, but separate from each other. No hunting around for 
specs. We've moved things in and out of core enough to know this 
organization is probably the best/most useful.


Jim Amsden, Senior Technical Staff Member
ELM Quality Manager
919-525-6575

**Comment by berezovskyi** [comment]
I didn’t suggest putting them in another repo but to separate them in different folders. I would even support putting different specs into different folders depending on their status. I don’t want to mix specs we are actively working with the ones that have not been touched in the last 5 years.

So, how about this:

```
specs/
  main/
    core-3.0/
    trs-3.0/
  domains/
    rm-2.1/
  inactive/
    actions-2.0/
```

--
–Andrew.

Från: Jim Amsden <notifications@github.com>
Svara till: oasis-tcs/oslc-core <reply@reply.github.com>
Datum: fredag, 3 maj 2019, W18 14:27
Till: oasis-tcs/oslc-core <oslc-core@noreply.github.com>
Kopia: Andrii Berezovskyi <andriib@kth.se>, Author <author@noreply.github.com>
Ämne: Re: [oasis-tcs/oslc-core] Reorganise the repo layout (#27)

Each spec is in a separate folder under specs, including core, trs, query,
config management, and all the domain specs. This keeps them all organized
in a single place, but separate from each other. No hunting around for
specs. We've moved things in and out of core enough to know this
organization is probably the best/most useful.


Jim Amsden, Senior Technical Staff Member
ELM Quality Manager
919-525-6575

**Comment by jamsden** [comment]
They are all in different folders, named by their short name, but all 
under the specs root folder where one might expect to find them.


Jim Amsden, Senior Technical Staff Member
ELM Quality Manager
919-525-6575

**Comment by berezovskyi** [comment]
Ok. Jim, how should I change the current `specs` folder to make it ready for your layout proposal? Can I just move the HTML files from the `specs` folder into subfolders directly?

Also, `spec/contexts` is not a spec.


```
.
├── Templates
│   └── OSLC-Core-publishing-instructions
├── open-services-vocabs
├── pub
├── reviews
├── specs
│   ├── am
│   ├── asset
│   ├── auto
│   ├── cm
│   ├── config
│   ├── contexts
│   ├── core
│   ├── ems
│   ├── images
│   ├── perfmon
│   ├── qm
│   ├── query
│   ├── recon
│   ├── rm
│   ├── schema
│   └── trs
├── styles
└── supporting-docs
    └── sketch-images
```

**Comment by berezovskyi** [comment]
`spec/images` is not a spec either.

**Comment by berezovskyi** [comment]
Jim, as a compromise, could we rename the domain spec folders in the process into `domain-cm`, `domain-rm` etc?

**Comment by berezovskyi** [comment]
`spec/schema` is not a spec either.

**Comment by jamsden** [comment]
Yes, just move the content from their current folders into the new folders under specs/*
specs/context folder belongs in new specs/core/context folder, its core specific content.
specs/images folder belongs in new specs/core/images folder too.
I prefer to keep the folder names to match the common spec names, domains really isn't a concept we need any more, its just OSLC OP.

We don't break up core because its a single multi-part specification.

**Comment by ndjc** [comment]
"I would even support putting different specs into different folders depending on their status.”

I would definitely oppose this - I would not want the repo URIs changing back and forth over time.

Nick.

**Comment by ndjc** [comment]
Are we finished with this reorg now?

**Comment by berezovskyi** [comment]
Yes
