### ISSUE TITLE
oslc_qm:status is an undefined property

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#270]
It is referenced in testresult.ttl as a typically read-only string that describes state of the test result, but it is not defined in quality-management-vocab.ttl. Shape checker didn't find this?

**Comment by berezovskyi** [comment]
I don't think QM is checked as part of the build. Please edit this file to update the settings: https://github.com/oslc-op/oslc-specs/blob/master/.circleci/config.yml
