### ISSUE TITLE
References are not shown in the Query spec

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#291]
Current WD is not showing References: https://oslc-op.github.io/oslc-specs/specs/query/oslc-query.html

`localBiblio` key contains this entry, for example:

		"FULLTEXT-SEARCH": {
          title: "Full-text search",
          href: "http://en.wikipedia.org/wiki/Full_text_search",
          publisher: "https://en.wikipedia.org"
        }, 

It is referenced in the body:

```
   <li>A full-text search based on one more search terms [[FULLTEXT-SEARCH]]. [...]
```

ReSpec 2.1.13, 2 errors:

1. conf.license must be set
1. Error loading references from 'https://labs.w3.org/specrefs/bibrefs?refs=RFC2119,FULLTEXT-SEARCH,OSLCCore3,LDP,WEBARCH,HTTP11,OSLCCM,RDF-SPARQL-QUERY,OSLCCore2,EBNF,OSLCShape,OSLCQuery2': error ()

What has to be fixed?

**Comment by berezovskyi** [comment]
cc @DavidJHoney

**Comment by berezovskyi** [comment]
Same thing across the board:
 
https://oslc-op.github.io/oslc-specs/specs/cm/change-mgt-spec.html

https://oslc-op.github.io/oslc-specs/specs/rm/requirements-management-spec.html

https://oslc-op.github.io/oslc-specs/specs/qm/quality-management-spec.html

https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html

**Comment by berezovskyi** [comment]
I just tested the QM 2.1 spec @ PSD02 with

https://cdn.jsdelivr.net/gh/oasis-tcs/tab-respec/builds/respec-oasis-common-XXX.js

where XXX is:

- 2.0.0
- 2.0.9
- 2.1.0
- 2.1.5
- 2.1.10
- 2.1.13

And no references show up. Also, no error appear in the dev console. @DavidJHoney found http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/csprd03/part1-overview/oslc-core-v3.0-csprd03-part1-overview.html#references to be one of the latest places where refs work.

**Comment by ndjc** [comment]
biblio.js is crashing out with no error in the dev console, sometime in or immediately after the ajax call to get the refs from the W3C server. Change in that server for this new year? Service no longer available?

**Comment by berezovskyi** [comment]
Update: after 60s I got an error

> Error loading references from 'https://labs.w3.org/specrefs/bibrefs?refs=OSLCCore3,RFC2119,OSLCQM1,OSLCCore2,OpenIDConnect,OSLCPreview,OSLCCoreVocab,OSLCShapes,LDP,WEBARCH,HTTP11,OSLCQM2,OSLCCM20,OSLCRM20,LDPPatch': error ()

And from Chrome

> GET https://labs.w3.org/specrefs/bibrefs?refs=OSLCCore3,RFC2119,OSLCQM1,OSLCCore2,OpenIDConnect,OSLCPreview,OSLCCoreVocab,OSLCShapes,LDP,WEBARCH,HTTP11,OSLCQM2,OSLCCM20,OSLCRM20,LDPPatch net::ERR_HTTP2_SERVER_REFUSED_STREAM

I guess this might be the reason. We might have to rebuild ReSpec to handle the refspec service being down.

**Comment by berezovskyi** [comment]
My change from https://github.com/oasis-tcs/tab-respec/pull/29 got me this:

![image](https://user-images.githubusercontent.com/64734/72090552-932d4e00-330e-11ea-9864-91000d979591.png)

But now some references are missing because they were loaded from the refspec server before.

**Comment by berezovskyi** [comment]
Tracking in https://github.com/oasis-tcs/tab-respec/issues/30. I just pushed another change to ReSpec switching the API URI.
