### ISSUE TITLE
QM title shall contain "Version" word

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#298]
- [x] Title spec
- [x] Title vocab
- [x] Citation spec
- [x] Citation vocab
- [x] Additional artifacts spec
- [x] Additional artifacts vocab

**Comment by paul-knight** [comment]
Also fix in "Additional artifacts" in each part (not sure if ReSpec will do this automatically)

**Comment by berezovskyi** [comment]
WARN! @jamsden @jadelkhoury for your specs too.
