### ISSUE TITLE
Editing changes resulting from publishing Core PSD04

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#303]
- [x] Part 6 has directly linked references to other specifications (e.g., RDF and XML Schema cited in conformance clause RS-21) which should probably be handled as citations of References.
- [x] Resolve remaining issues as necessary for COS
- [x] Publish update vocabulary and shapes
- [x] add the expected meta "description" tags to the seven HTML files, and listed the tag text in the github ticket so they can be incorporated by the OSLC Editors in future stages if desired. meta description tags (using text from the "Abstract" sections) to the HTML files for each of the seven parts e.g.,:  Part 1 (oslc-core) <meta name="description" content="This specification defines the overall approach to Open Services for Lifecycle Collaboration (OSLC) based specifications.">
- [x] In oslc-core (Part 1), noted that about 12 references to other Parts in the Conformance section (Section 6) refer specifically to the csprd03 publication, rather than to the current stage (i.e., they don't use relative links). See CORE-40 through -45, plus six instances in the text above the conformance table itself. (add to issues for next stage)
- [x] In resource-preview (Part 3), conformance clause RP-22 refers to "XML Representation Format". Although this is hyperlinked to a resource on open-services.net, note that Appendix B is entitled "XML Representation Format", so this may be ambiguous. (possible issue)
- [x] attachments.html (part 5) and core-vocab.html (part 7) contain doubled horizontal lines (<hr> tags) just before Section 1.
- [x] resource-shape.html (Part 6) contains tripled lines before Section 5.

**Comment by berezovskyi** [comment]
@chet-ensign we are planning to fold these changes into PS04. Are you ok with these? Or do we need to make a PSD05 for this?

**Comment by OASIS-OP-Admin** [comment]
PSD or PS? I don't think the PGB has voted to approve this as a Project Specification yet, correct? As a PSD, I'm fine with folding the changes in. So long as you all are happy with your ability to trace backwards when you need to, that's fine. Once it gets approved as a PS, we'll need to keep sequential iterations more distinct. Make sense?

**Comment by berezovskyi** [comment]
You mean if it was a PS03, you would insist on making PSD04>PS04>COS04 instead of making these changes directly to the COS03 draft?

**Comment by jamsden** [comment]
@chet-ensign, you are correct, we have not yet voted to approve core PSD04 as PS04. What we were asking is if we could fold these changes into the documents, and promote as PS04 through that PGB vote, or do we need to do in in a separate PSD05 which would then be promoted to PS05.

**Comment by OASIS-OP-Admin** [comment]
@berezovskyi - yes. If approved as a PS, the work is equivalent to a CS on the standards side. You could approve for COS with non-material changes just as you can on the TC side but if the changes were judged material, they would need to go back to PS04. 

Also, in keeping with the conventions for standards track work, the PS number will start with 01.

**Comment by OASIS-OP-Admin** [comment]
@jamsden the changes can go into the PSD04. As I noted, the PS will be the first time approved so it is PS01, independent of the PSD## that produced it.

**Comment by jamsden** [comment]
Resolved by https://github.com/oslc-op/oslc-specs/pull/360
