### ISSUE TITLE
Inconsistent citation references across 7 parts of OSLC Core 3.0

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#305]
Here are Citation forms for the 7 parts of core:
[OSLC-Core-3.0-Part1]
[OSLC-Discovery-3.0]
[OSLC-ResourcePreview-3.0]
[OSLC-Dialogs-3.0]
[OSLC-Attachments-3.0]
[OSLC-Shapes-3.0]
[OSLC-CoreVocab-3.0]

There are several inconsistencies:
1. All but the first station ends with "3.0".
2. All but the first uses part of the title not the part number.
3. Two of them use Core, the other 5 do not. But one use of Core is hyphenated the other not.

Should we change these to:
[OSLC-Core-Overview-3.0]
[OSLC-Core-Discovery-3.0]
[OSLC-Core-ResourcePreview-3.0]
[OSLC-Core-Dialogs-3.0]
[OSLC-Core-Attachments-3.0]
[OSLC-Core-Shapes-3.0]
[OSLC-Core-Vocab-3.0]

**Comment by berezovskyi** [comment]
Chet gave us a relative carte blanche, we are free to proceed as suggested.

--
/Andrew
(from phone)

On 30 Jan 2020, at 16:34, David Honey <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are Citation forms for the 7 parts of core:
[OSLC-Core-3.0-Part1]
[OSLC-Discovery-3.0]
[OSLC-ResourcePreview-3.0]
[OSLC-Dialogs-3.0]
[OSLC-Attachments-3.0]
[OSLC-Shapes-3.0]
[OSLC-CoreVocab-3.0]

Should we change these to:
[OSLC-Core-Overview-3.0]
[OSLC-Core-Discovery-3.0]
[OSLC-Core-ResourcePreview-3.0]
[OSLC-Core-Dialogs-3.0]
[OSLC-Core-Attachments-3.0]
[OSLC-Core-Shapes-3.0]
[OSLC-Core-Vocab-3.0]

**Comment by jamsden** [comment]
However, I'm not motivated to republish all the existing documents to achieve this consistency unless there's something else we need to change.

**Comment by jamsden** [comment]
I see little reason for changing these at this point. Reopen if you strongly disagree.
