### ISSUE TITLE
Address Query specification review comments

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#31]
From Paul Knight:

- [ ] We have transitioned the OASIS web site and document repository to use HTTPS instead of HTTP for almost all URIs going forward. This actually introduces some transitory issues in references to older specifications. If older HTML specifications which use .css files (unfortunately, this includes OSLC specs) are referenced using HTTPS, then the .css scripts will not be executed, and the visible document formatting will be affected. What this means in practical terms is that the "Previous version" hyperlinks on the front page should continue to use HTTP the next time a new stage of an existing specification is published. Later, when the Previous version links point to a document published as using HTTPS, they can use HTTPS. We should be able to track and correct these issues for you.

jra: I don't think this will impact Open Project URIs and their use of css, but we may have one round of revisions where the Previous Version needs to be http.

- [x] You are using a somewhat obsolete structure for the IPR Policy statement, which occurs twice in each specification: first as the third paragraph in the "Status:" section on the front page, and second as the IPR Policy section (usually Section 1.1). Specific changes desired:  remove "being" from "This specification is being provided" in third paragraph of Status section, and then copy the entire paragraph to use as the IPR Policy Section (1.1).  So the text at both places should be:

This specification is provided under the RF on Limited Terms Mode of the OASIS IPR Policy, the mode chosen when the Technical Committee was established. For information on whether any patents have been disclosed that may be essential to implementing this specification, and any offers of patent licensing terms, please refer to the Intellectual Property Rights section of the TC’s web page (https://www.oasis-open.org/committees/oslc-core/ipr.php). 

jra: this no longer applies as the IPR policy is removed from open project specifications and replaced with a reference to the chosen license.

- [x] 3. Please ensure that the approved ZIP file contains all of the relevant artifacts.  For OSLC-Query, I had to go fishing in the TC's SVN repository to get the diagram at the top of Section 3. (images/CoreDiscoveryUML.png)

jra: the open project publishing process is as yet unknown. But it will likely still involve ReSpec rendering of static HTML and references to images and styles that will need to be included in the publish process. Hopefully we will be able to script the publish process to remove manual activities that can result in errors.

- [x] 4. Widely applicable across the OSLC specifications - the web site at open-services.net has apparently reorganized the storage of all of the Version 2 OSLC files, so that all of the links to those documents are broken.  The fix to the links is fairly simple, since the documents appear to all be available at "https://archive.open-services.net/" instead of the address "http://open-services.net/".  I made this change to the references in OSLC-Query-v3.0. You will need to apply this to future publications of all OSLC documents which contain references to these V2.0 documents. If you have access to the open-services.net systems, you may be able to arrange for some kind of redirection at the site, to avoid reworking all of the OASIS documents.

jra: this should be fixed with the effort Andrew has just done to update all the redirects to the older specs in the archive.
  
- [x] 5. We have changed the OASIS headings text colors and logo (as in OSLC-Domains, for the OSLC-AM v2.1 specification [1]).  We'll work with you to get these changes into your future publications. It mostly involves including a new version of the "spec.css" file, and updating the reference to the logo file.

jra: this no longer applies as the open project has its own icon which is handled by ReSpec.

- [x] 6. "Nice-to-have" - If you are able to set up your ReSpec environment to generate a horizontal rule (line) using the  <hr> tag in the HTML, just before each major section, that will be helpful for publication going forward. (It is already being generated - at least in OSLC-Query - after the OASIS logo, before the "Notices" section, and before and after the Table of Contents. I had to add it before Section 2, 3, etc. In addition to following the OASIS style for HTML, this is also our trigger for a new page in the PDF, when we generate it from the HTML.

jra: this looks to be done as part of the open project ReSpec updates.

- [x] 7. I noted that there's a case where the same text appears in two different conformance clauses, which (in Section 10 of OSLC Query) causes the link for query-41 to jump to its duplicate, query-27 (which I just noted, does not show up in the table in Section 10). Hmmm....

I think that covers the items I noted.  I'm not submitting this as a formal Public Review comment, so there's no need for any specific response or comment-tracking. (Although maybe item 7 should be noted for some attention...) 

- [ ] Accessibility Checker: https://achecker.ca/checker/index.php when given the HTML version of OSLC Query Version 3.0 https://docs.oasis-open.org/oslc-core/oslc-query/v3.0/csprd01/oslc-query-v3.0-csprd01.html 

From Patrick Durusau <patrick@durusau.net>

The [TAB Issues](https://issues.oasis-open.org/projects/TAB/issues/TAB-1660?filter=allopenissues) are the formal review issues that must be addressed. See issues where affectsVersion = "OSLC Query Version 3.0". Use "OSLC Query Version 3.0" filter

It isn't necessary to acknowledge each comment separately. A single  email acknowledging this email will be sufficient.   If the TC chooses to ?defer? resolution of an issue to a later version,  please choose Defer Issue under Available Workflow Actions (after opening the issue).   When the TC has acted on these issues, I would appreciate a pointer to the TCs resolution as the TAB is tracking the resolution of comments from TAB members.

TAB issues that require action:

- [x] TAB-1658 Caption on all tables
- [x] TAB-1656 RDF/XML bib ref for XMLLiteral standard
- [x] TAB-1655 reference XML Schema in oslc.where clause
- [x] TAB-1654 incorrect citations, use  http://docs.oasis-open.org/templates/ietf-rfc-list/ietf-rfc-list.html http://docs.oasis-open.org/templates/w3c-recommendations-list/w3c-recommendations-list.html 
- [x] TAB-1653 non-normative terminology
- [x] TAB-1652 conformance clauses vs normative statements
- [x] TAB-1651 implementation vs server
- [x] TAB-1650 implementations of this specification = OSLC query capability implementations or OSLC Query server
- [x] TAB-1649 Section 3 reference to discovery image
- [x] TAB-1648 duplicate anchors in oslc.where clause table
- [ ] TAB-1647 fix permanent redirects

**Comment by jamsden** [comment]
TAB issues that apply to all oslc-op specifications

TAB issues that require action:

- [TAB-1658](https://issues.oasis-open.org/browse/TAB-1658) Caption on all tables - All tables should bear captions and numbers. Moreover, Table N, is the proper way to reference a table.
- [TAB-1652](https://issues.oasis-open.org/browse/TAB-1652) conformance clauses vs normative statements
- [TAB-1651](https://issues.oasis-open.org/browse/TAB-1651) implementation vs server - we should avoid the therm implementations and say specifically if we are dealing with a client or (usually) a server.
- [TAB-1647](https://issues.oasis-open.org/browse/TAB-1647) fix permanent redirects - http://validator.w3.org/checklink identifies permanent redirects, any of these URLs in the specifications should be updated to use their new URL and avoid the redirect.

**Comment by ndjc** [comment]
There are some permanent redirects that should **NOT** be updated:



1. http://www.ibm.com/ is redirected to https://www.ibm.com/us-en/?ar=1
This is a locale-specific redirect, and should not be hard-coded in any spec source.

1.  http://open-services.net/ns/core redirected to http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/oslc-core-v3.0-part7-core-vocabulary.html (and all similar redirects from http://open-services.net/ns/)
URIs of the form http://open-services.net/ns/* **MUST NOT** be changed. This is a content negotiation redirect, and moreover, it is also a URI used in RDF. Replacing the http://open-services.net/ns/* URIs with their redirected equivalent would result in different and incorrect RDF.

**Comment by berezovskyi** [comment]
> There are some permanent redirects that should NOT be updated

We've been at this before. Permanent redirects should be updated precisely because they are permanent. If we think it does not make sense, the only correct way is to make the redirects non-permanent.

IBM is obviously wrong in making that redirect permanent. But hey, good luck getting the corporate IT to fix that 😹 

Now, I checked the things I have control over and here are the redirects:

- http://open-services.net/ns/core to https://open-services.net/ns/core PERMANENT
- https://open-services.net/ns/core is 200 OK with JSON-LD payload by default.
- - https://open-services.net/ns/core is 303 See Other (not 301!) to http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/oslc-core-v3.0-part7-core-vocabulary.html when asking for HTML. 

I think that while we theoretically may change links in the spec to point to httpS://open-services.net/ns/core, it may lead to more confusion than necessary. If TAB does not see it our way, I can change the first redirect to 302 temp redirect 🙉

**Comment by berezovskyi** [comment]
Oh wait, actually there is a 303 See Other in the IBM redirect chain too:

```
curl -IL http://ibm.com -H 'Accept: text/html'
HTTP/1.1 301 Moved permanently
Location: https://ibm.com/
Connection: close
Cache-Control: no-cache
Pragma: no-cache

HTTP/1.1 301 Moved Permanently
Date: Wed, 31 Jul 2019 15:28:25 GMT
Cache-Control: max-age=301
Expires: Wed, 31 Jul 2019 15:33:26 GMT
Content-Type: text/html
Location: https://www.ibm.com/
Strict-Transport-Security: max-age=7776000
Content-Security-Policy: upgrade-insecure-requests
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff

HTTP/2 303
server: AkamaiGHost
content-length: 0
location: https://www.ibm.com/se-en/?ar=1
date: Wed, 31 Jul 2019 15:28:25 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-security-policy: upgrade-insecure-requests
strict-transport-security: max-age=31536000

HTTP/2 301
x-powered-by: Express
location: //www.ibm.com/se-en
content-length: 232
date: Wed, 31 Jul 2019 15:28:25 GMT
x-ibm-from-redirect: Yes

HTTP/2 200
server: nginx
```

https://www.ibm.com/ is the last chained permanent redirect. All http://www.ibm.com links shall be updated to point to https://www.ibm.com/.

**Comment by ndjc** [comment]
Changing http:// URIs to https:// for things like ibm.com is of course fine, and should be done - in fact, I have already made several such changes in places I have noted. If doing this leaves no remaining permanent redirects, then good, but if it leaves any locale-specific or similar redirects that happen to use 301, then that's too bad - we have no real influence over the configuration of ibm.com or similar corporate sites.

Changing usage of namespace URIs such as http://open-services.net/ns/core cannot ever be done; as far as RDF would be concerned, these are different URIs, and so do not identify the same types. Adding owl sameAs or other equivalence assertions is not an adequate solution, since few if any OSLC implementations use any significant inferencing.  There is quite a bit of discussion on this topic of RDF vs. https on the web, with no good conclusions yet that I can see.  Yes, you could avoid some of the issues by changing the redirection to be other than 301 for open-services.net/ns/ (and _possibly_ jazz.net/ns/), but that would not fix any type redirects for non-OSLC specs.

My primary point is this: changing the specs blindly replacing ALL permanent redirects is not the right approach. Instead, the editor needs to work out what the series of redirects involves, and which ones should or should not be changed, and if any that should not be changed can and should be fixed by the site owner.

**Comment by berezovskyi** [comment]
> Changing http:// URIs to https:// for things like ibm.com is of course fine, and should be done - in fact, I have already made several such changes in places I have noted. If doing this leaves no remaining permanent redirects, then good

Yes

> Changing usage of namespace URIs such as http://open-services.net/ns/core cannot ever be done; as far as RDF would be concerned, these are different URIs, and so do not identify the same types. 

I perfectly know that. What I meant by confusion is that we can only change those links in the HTML spec but the RDF URIs shall remain unchanged.

**Comment by ndjc** [comment]
I'm not sure what you are suggesting. If you are saying that we might change the actual href of a vocabulary term link in the HTML of a spec to https while keeping the visible text as http, I think it could lead to more than confusion - it would lead to errors if a user used 'Copy link' in the browser and pasted the https URI for an RDF term into their code. I would view that as unacceptable.

**Comment by berezovskyi** [comment]
I would suggest to change IBM links to have HTTPS and leave the open-services.net links as is.

**Comment by berezovskyi** [comment]
@jamsden please switch the spec to use https://cdn.jsdelivr.net/gh/oasis-tcs/tab-respec@v2.1.8/builds/respec-oasis-common.min.js and see how many issues it fixes.

**Comment by berezovskyi** [comment]
Also, I guess there was never a PSD published, renaming the title accordingly.

**Comment by DavidJHoney** [comment]
Currently working on editing query spec:
[TAB-1658 Caption on all tables](https://issues.oasis-open.org/browse/TAB-1658) - completed edit.

**Comment by berezovskyi** [comment]
Thanks @DavidJHoney!

Re incorrect citations: did you push a branch and open a draft PR? I can't check otherwise.

Re license: use the following code.

      license: "cc-by-4",
      additionalLicenses: [{
        licenseName: "Apache License 2.0",
        licenseURI: "https://www.apache.org/licenses/LICENSE-2.0",
      }],

Re error loading references: super wierd. Are you using ReSpec 2.1.13?  https://cdn.jsdelivr.net/gh/oasis-tcs/tab-respec@v2.1.13/builds/respec-oasis-common.min.js

Re TAB-1652: feel free to edit https://github.com/oasis-tcs/tab-respec/blob/master/js/templates/conformance-table.html#L3 and make a pull request, this will go into 2.1.14. @paul-knight just to be sure, this is the right edit and should be reflected in all OSLC PSDs going forward?

P.S. Checked off the items in the issue description you described as completed, looks easier to track progress.

**Comment by DavidJHoney** [comment]
All I have done so far is to use the Git integration in Eclipse. clone the repo, set it as an Eclipse project, and made edits to the query/oslc-query.html file.

I have asked before about what process I should follow, but no one has given me an easy guide. Previously, I was using the SVN Eclipse plugin with the old repo, and have also been using RTC for source code control in Eclipse.
So I do not understand your question “did you push a branch and open a draft PR?”.
In the Eclipse project explorer I see:

[cid:image001.png@01D5C24A.AF10F430]

In the Git Repositories Eclipse view. I see the following context menu options:

[cid:image002.png@01D5C24A.AF10F430]

So what are the steps I should be following?


Re Respec: The oslc-query.mthml file includes this:
<script src='https://raw.githack.com/oasis-tcs/tab-respec/master/builds/respec-oasis-common.js' async
    class='remove'></script>

This was whatever was placed in that file as it was setup in Github.
I see other core specs using something different. For example, core/discovery.html uses:
  <script src='https://raw.githack.com/oasis-tcs/tab-respec/master/builds/respec-oasis-common.js' async
    class='remove'></script>
I will try that. It seems to have fixed one of the errors.

I’m not clear where you are suggesting those additional lines should go – into the body starting at line 9 that starts with “var respecConfig = {“?

If I open core/discovery.html in the Eclipse web browser, it reports the following errors:
[cid:image003.png@01D5C24B.D08C77A0]
Given that I have the whole spec tree (see below), should these errors be reported?

[cid:image004.png@01D5C24B.D08C77A0]

David
