### ISSUE TITLE
OSCL Core does not describe use of a repeated parameter

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#313]
Neither OSLC Core nor Query specifications describe the use of a repeated parameter value. For example, for oslc.properties (selective properties), the syntax is described as:
    `oslc_properties ::= "oslc.properties=" properties`
    `properties      ::= property ("," property)*`

So if an OSLC client wants to specify multiple properties, they SHOULD specify a single parameter (e.g. GET http://host:port/resource?oslc.properties=dcterms%3Atitle%2Cdcterms%3Adescription).

However, some clients might assume that the query parameter can be repeated (e.g. GET http://host:port/resource?oslc.properties=dcterms%3Atitle&oslc.properties=dcterms%3Adescription). This latter usage is not described, and some implementations might support this and others not.

I think the specification should be more explicit about this. I don't think it can make support for this a MUST because that would make many existing implementations non-conformant. If the spec makes this a SHOULD or a MAY, then I think it should provide _client_ guidance to not use this if maximum portability across implementations is required. I don't think the spec should forbid supporting it - that would be too prescriptive.

**Comment by jamsden** [comment]
Perhaps we should allow both with MAY, but SHOULD for separation by comma. See https://www.moesif.com/blog/technical/api-design/REST-API-Design-Best-Practices-for-Parameters-and-Query-String-Usage/ which addresses this directly for query parameters with multiple values (search for multiple).

**Comment by jamsden** [comment]
We discussed this issue today and decide there is nothing we can say that would generally apply to all muli-valued query parameters. The best we can do is define the query parameter syntax in the OSLC spec, and assume that servers will implement them and clients will use them as described.
