### ISSUE TITLE
Resource shape for oslc:Dialog missing from Core 3.0 discovery spec

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#318]
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/discovery.html is missing the resource shape for selection dialog. The shape is present in the Core 2.0 spec.

**Comment by jamsden** [comment]
Dialogs are covered in dialogs.html and aren't redundantly covered in discovery. Section 4.5 Resource User Interface Delegated Dialogs Discovery links to dialogs.html.
