### ISSUE TITLE
Whether RDF shall have precedence over HTML

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#323]
Many people on the call today were confused by https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/oslc-core.html#versionCompatibility:

> It is worth noting that in OSLC 2.0 specifications, normative specification text had precedence over machine-readable content, as opposed to this specification.

I take it as that OSLC 3 reversed course and RDF is now the truth. @jamsden wants a vote on this.

I think it is very important we keep the change and do not revert. Many products do not trust our published vocabs and keep a copy. Also, silly mistakes were discovered in the past in the vocab files. I think we need to treat RDF files as a key item of the spec.

**Comment by jamsden** [comment]
I would rather the .ttl files in the repo are normative, and the OASIS published specifications are just representations of these, processed through ReSpec for readability. 

Let's do what we need to do re: publishing and additional content referencing to make this happen. Then the sections of the vocab.html specs that render the shapes in the HTML tables would be marked non-normative.

**Comment by ndjc** [comment]
Can we now close this as YES, the RDF source is normative? In both the above comments, Andrew and Jim agree that the Turtle files are the normative source. We had some debates about how/where those definitive files should be published, but I believe we did agree on that fundamental rule.

**Comment by berezovskyi** [comment]
I close this with the resolution YES following the call yesterday and all three of us here being in favour of it.
