### ISSUE TITLE
Whether RDF shall be published in multiple formats on open-services.net

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#324]
I think it is important to support [conneg](https://www.w3.org/DesignIssues/Conneg), given that we say our users SHOULD implement it. Moreover, it's already implemented (see [this](https://github.com/oslc-op/website-content-negotiation)) and the process requires copying the vocabs anyway (we can fully control `Content-Type` and do conneg on our own servers, see [this](https://github.com/oslc-op/website/tree/master/content/ns)).

If you have Jena on your machine (I imagine all of us do, for Fuseki at the very least), the command in the README takes a few seconds to run. I can also look in to Github Actions to automate it but don't see it as a bottleneck now.

**Comment by jamsden** [comment]
Let's not make too much of the different representations of RDF. It was probably not that helpful for the semantic web to invent so many different ways of saying the same thing, at the expense of not doing lots of other things that might have made RDF more useful (I'm also thinking of all the different dialects of RDFS and OWL).

Hopeful modern tools can accept and provide any of the common RDF content types, focusing on Turtle and JSON-LD as specified in LDP, and we can move on from this distraction.

**Comment by berezovskyi** [comment]
We decided to keep conneg in its current form during the last meeting, the following formats will be published:

- Turtle (original)
- RDF/XML (for legacy purposes)
- JSON-LD
- N-Triples (for broad compatibility)
