### ISSUE TITLE
Add extra properties to the vocab to make it easy to tell apart old ones from the current

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#326]
Problem: if we encourage users (as we should, see [Linked Data Rule no. 3](https://www.w3.org/DesignIssues/LinkedData.html)), they have no way of telling how old the vocabulary they are looking at is. The problem gets worse if they store it on disk.

Proposed solution: add some RDF properties, just like DCTerms does. See proposal in https://github.com/oslc-op/oslc-specs/pull/325.

Please note that I strongly disagree with placing _information_ into URIs because [URIs shall be opaque](https://www.w3.org/DesignIssues/Axioms.html#opaque).

**Comment by berezovskyi** [comment]
Fun fact: I went looking for a tag predicate following a request from Jim on https://lov.linkeddata.es/dataset/lov/terms?q=tag&page=2 and I found a perfect property:

![image](https://user-images.githubusercontent.com/64734/83786133-985eb100-a692-11ea-8d6f-8c856425c37a.png)

**Comment by jamsden** [comment]
Unfortunately users do have to look at URLs as they type them, understand the implications of http vs. https protocols, the server and port have to be known, and all fragment identifiers and query parameters of necessity include user provided information.

So I don't think we need to be purists here. It is not putting semantic information in URL paths that makes them opaque or not, it wether anything explicitly relies on knowing that information.

**Comment by ndjc** [comment]
I'm not really sure why this issue is separate from issue 326: is it that #325 asks if extra properties are required at all - if they are the right solution, and #326 asks (presuming the response to #325 is Yes) what those extra properties should be? So if this issue were to be closed agreeing that extra properties are not required, then #326 would be closed as moot?

**Comment by ndjc** [comment]
I don't like the idea of maintaining any extra properties manually - that guarantees they'll be wrong sometime. If we really need to do this, we should also try to automate it as much as possible.

**Comment by berezovskyi** [comment]
One is an issue and another is a PR with an example? Ofc is the issue is closed as wontfix, PR gets scrapped.

Cheers,
Andrew

________________________________

**Comment by berezovskyi** [comment]
Just a reminder: you should suggest which properties to keep in #325.

**Comment by ndjc** [comment]
@berezovskyi have we not now fixed this by adding the extra properties on vocabularies and shapes (ResourceShapeConstraints)?

**Comment by ndjc** [comment]
@berezovskyi  - see previous comment - can we not close this issue now? If we want further automation in the future, we should create a new issue to describe precisely what we intend.

**Comment by berezovskyi** [comment]
@ndjc I trust your judgement. In the future, feel free to close the issue with the comment "Please reopen if ..." for the sake of expediency.
