### ISSUE TITLE
Do we need to publish shapes in multiple files?

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#328]
We did not get to discuss this but I think all shapes shall be combined into a single file and published this way.

Especially given #326, #324, it will be too expensive to produce many files (unless we use a tool like Pubby).

**Comment by jamsden** [comment]
I'm ok with that. One issue: the separate files make it easy to show the shapes in different sections in the respec generated vocab.html specs. This is because its easy to have a separate section with a separate div for each shape2spec conversion.

**Comment by berezovskyi** [comment]
What do you mean?

![image](https://user-images.githubusercontent.com/64734/83798447-90a80800-a6a4-11ea-8431-5a3fe4bed2fe.png)

**Comment by jamsden** [comment]
That's a different section for every class. The other approach allows you to have a section with more than one class. But maybe that's not needed.

**Comment by jamsden** [comment]
Actually ignore this, the sections are independent of the div/shapToSpec items. Put as many as you want whereever you want. Sorry for the distraction.

**Comment by ndjc** [comment]
For Config Management, I group multiple shapes into one source file where those shapes are related. I do not want to merge ALL shapes into a single file - that gets too large and difficult to find the content I want to change.

**Comment by berezovskyi** [comment]
Do we agree to deliver all shapes for a domain in a single file? I think we can close this issue following the Thu call.

**Comment by jamsden** [comment]
Ok with me.

**Comment by berezovskyi** [comment]
@ndjc?

**Comment by berezovskyi** [comment]
Agreed to use a single file
