### ISSUE TITLE
Update all specs to use the new Open Project ReSpec

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#33]
All specs should now include ReSpec from https://raw.githack.com/oasis-tcs/tab-respec/master/builds/respec-oasis-common.js. Specs should no longer contain any references to github.com/ndjc or ndjc.github.io.

**Comment by jamsden** [comment]
```
<script src='https://raw.githack.com/ndjc/respec/oasis-op/builds/respec-oasis-common.js' async class='remove'></script>
<script src='https://raw.githack.com/oasis-tcs/tab-respec/master/builds/respec-oasis-common.js' async class='remove'></script>

//        WD      Working Draft
//        PSD     Project Specification Draft
//        PSPRD   Project Specification Public Review Draft
//        PS      Project Specification
//        COS     Candidate OASIS Standard
//        OS      OASIS Standard
//        Errata  Approved Errata
//        PND     Project Note Draft
//        PNPRD   Project Note Public Review Draft
//        PN      Project Note
```

**Comment by jamsden** [comment]
Most of the old specs used https://ndjc.github.io/respec/builds/oasis/respec-oasis-common.js

**Comment by berezovskyi** [comment]
Do we need to edit any of the specs on SVN?

**Comment by berezovskyi** [comment]
For example http://docs.oasis-open.org/oslc-core/oslc-query/v3.0/csprd01/oslc-query-v3.0-csprd01.html references a CSS file from Nick's repo.

**Comment by jamsden** [comment]
The old ReSpec URL is being retained for a year. So that should be long enough for the SVN content to be irrelevant if it isn't already.

Any references in specs to ReSpec styles is likely just a mistake.

**Comment by jamsden** [comment]
ReSpec rendering does include its own styles in the generated HTML, that's fine.
