### ISSUE TITLE
Vocab anchors do not match shape names

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#334]
**Problem**
Similar to a vocab class/property conneg, we expect the same to work on shapes.

The TestCase shape has an anchor of https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/quality-management-vocab.html#testcase. However, the TestCase shape has a local name of `#TestCase` (see [shape](https://github.com/oslc-op/oslc-specs/blob/c9e4357031f49fe352362f3526745af84f6a0e92/specs/qm/testcase.ttl#L33)). This will redirect to https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/quality-management-vocab.html#TestCase (note it's case-sensitive).

**Proposal**
We shall:

1. Rename the shape resource to `#TestCaseShape` or `#TestCaseResource` in RDF.
2. Change the [quality-management-vocab.html#testcase](https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/quality-management-vocab.html#testcase) anchor to `quality-management-vocab.html#TestCaseShape`

This will enable `-vocab.html` pages to be used both for the non-RDF conneg redirect for both vocabs and shapes without any conflicts.

**Comment by berezovskyi** [comment]
@jamsden @ndjc @jadelkhoury please provide your opinion, I will then incorporate it into #329.

**Comment by jamsden** [comment]
Definitely not #1 - it is not a good idea to put type information in a class name. And that would be a breaking change for existing implementations.

**Comment by jadelkhoury** [comment]
@jamsden just to be clear: To avoid breaking changes, are the implementations dependent on the vocab or shape urls? I'm also wondering if any are yet using QM 2.1.

option 2 is also breaking I guess?

**Comment by jamsden** [comment]
Yes. IBM Engineering Test Manager (formerly Rational Quality Manager) uses the QM vocab and shapes. In fact, these files came from the QM implementation.

**Comment by berezovskyi** [comment]
Original proposal:


1.     Rename the shape resource to #TestCaseShape or #TestCaseResource in RDF.
2.     Change the quality-management-vocab.html#testcase anchor to quality-management-vocab.html#TestCaseShape

**Comment by berezovskyi** [comment]
Alternative proposal:

1. Split every vocab part into 2 extra parts: vocab and shape.
2. Leave same anchors

Whoever votes for this will have to pitch in with with the split.

**Comment by ndjc** [comment]
Note that the two alternative proposals above are not mutually exclusive. A spec author must do one or the other, or both. For Config Mgmt and TRS, I expect to do both - for Config Mgmt, the vocab part was always separate from the shape tables, so I do not have any extra work for that.

**Comment by berezovskyi** [comment]
I agree that an option to do both would be most appropriate.

**Comment by berezovskyi** [comment]
> Changing all shape names to include a shape suffix for the purpose of allowing HTML redirects of vocab and shape namespace references to link to the correct section in the *-vocab.html document seems extreme to me. Yes, it's a solution to the problem, but it adds unnecessary and redundant information to names that I feel are important to good design.

Yes, it is redundant and not important. I feel that redundancy won't hurt given that many users have low semantic literacy. I don't see how the change be extreme and not important at the same time.

> Note that no other domain or any of the core shapes follow this convention. So this is a significant set of changes.

CfgM does. I don't think appending the suffix `Shape` to every shape resource will be that significant. At least not more significant than adding a new part to each spec.

> On the other hand, vocabulary terms and resource shape constraints are very different things, with different usages, compatibility conformance clauses, and different lifecycles. They aren't coupled in the same .ttl files, and they shouldn't be coupled in the same HTML specification file.

I think it's actually good to keep them in the same part given that many people might confuse the two. But can also split. No strong preference here.

> This is the least disruptive, and least impactful change to address the root problem.

Again, I do not see any disruption coming from appending `Shape` suffix to the URIs of the resources that:

- were never published
- had their (planned) URI changed a few times already:
  - https://localhost:9443/jazz/oslc_qm/contexts/_stJVgGfqEd24KMoDcFLfcQ/shape/resource/VersionedTestCase to
  - https://open-services.net/ns/qm/shapes/ps01#TestCase to
  - https://open-services.net/ns/qm/shapes/2.1/TestCase to
  - https://open-services.net/ns/qm/shapes/2.1/#TestCase

I really don't see how renaming once more to https://open-services.net/ns/qm/shapes/2.1/#TestCaseShape will hurt anything.

I am still in favour of shape resource URI renaming. If someone wants to split the vocab part on top of that, I am open if they make a PR.

**Comment by ndjc** [comment]
Just to keep the record clear - as discussed in the OP meeting today, there are no IBM product dependencies on the OSLC 3.0 shape URIs in any domain, QM or otherwise. There are dependencies on current jazz.net shape URIs, or QM installation-relative URIs, but these are completely separate shapes, since they include custom properties above and beyond those defined in OSLC (and we never defined a shape inheritance mechanism).

**Comment by berezovskyi** [comment]
@jamsden @jadelkhoury @DavidJHoney @axelreichwein please cast your vote for https://github.com/oslc-op/oslc-specs/issues/334#issuecomment-646095412 or the one below. We will decide next Thursday.

**Comment by berezovskyi** [comment]
@jadelkhoury I just recalled LyoD generates shapes with the same URIs as classes, doesn't it? Can you confirm OSLC spec shape URIs have no effect on LyoD/adaptor operation?

**Comment by jadelkhoury** [comment]
> @jadelkhoury I just recalled LyoD generates shapes with the same URIs as classes, doesn't it? Can you confirm OSLC spec shape URIs have no effect on LyoD/adaptor operation?

@berezovskyi LyoD is about defining own shapes, and not necessarily the OSLC domain specs. So, there the user can do whatever they want.
The shapes's URI are actually based on the server's URI (Plus "/shapes/resource_class_name")

I think you are confusing it with the DomainSpecification URI, which is actually the namespace for the Vocabulary terms.

**Comment by berezovskyi** [comment]
Thanks @jadelkhoury. I am not confusing that, but thanks for checking. The point I am trying to make for @jamsden is that Lyo code managed to work with existing products just fine in the past with the shape URI not being a 100%  match of the `open-services.net/ns/%spec%/shapes/%version%/%vocab_name%` pattern.

**Comment by berezovskyi** [comment]
@jadelkhoury @DavidJHoney reminder to vote on https://github.com/oslc-op/oslc-specs/issues/334#issuecomment-646095412 before the meeting today.

**Comment by jadelkhoury** [comment]
It feels that are many discussions in this thread. Original question was about the anchors into the HTML documents under OASIS. So, not really sure why there were later discussions on changing the URLs of the shapes under open-services. 
Why change to https://open-services.net/ns/qm/shapes/2.1/#TestCaseShape? Clearly, the "shapes" part of the URI make it clear that it is different from the TestCase vocab URI. so don't see the point of "#TestCaseShape"

So, if I am to stick to the original question and just leave a vote, I'd go for #2.

**Comment by berezovskyi** [comment]
Both a `TestCase` RDFS Class and a `TestCase` RDFS class for a shape cannot have the same anchor on a same page. Thus, we either need to change names so that `TestCase` and `TestCaseShape` can have different anchors on the same page or split the vocab/shape page into two (or do both as Nick suggests, which I support).

**Comment by DavidJHoney** [comment]
I don't feel strongly. Proposal 2 seems cleaner than Proposal 1, but that's a weak preference.

**Comment by jamsden** [comment]
Note that Resource Shapes are constraints unique to OSLC and SHACL might be something that would be a future consideration. So putting "Shape" at the end of the names tends to emphasize perhaps the wrong thing?

**Comment by berezovskyi** [comment]
We have agreed to do both in the call today: https://github.com/oslc-op/oslc-admin/blob/master/minutes/2020/2020-06-25.md#vocab-anchors
