### ISSUE TITLE
AM shapes use jazz_am prefix

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#336]
The spec declares oslc_am as a default prefix.

https://oslc-op.github.io/oslc-specs/specs/am/architecture-management-vocab.html

**Comment by jamsden** [comment]
What's the problem? The fact that there is more than one prefix defined in the spec? 

But a larger question is what is meant by "default prefix", This should probably be preferred prefixes.

**Comment by berezovskyi** [comment]
Jazz prefix is used in the normative part of the spec without having been defined. Isn’t it a problem?

**Comment by jamsden** [comment]
I added it to the namespaces in the shapes file, that's the only place jazz_am appears.

**Comment by berezovskyi** [comment]
but are the URIs and semantics different? can we just use oslc_am everywhere instead?

**Comment by jamsden** [comment]
the URIs are different, we can't use oslc_am everywhere. the jazz_am prefix is for the properties we are referencing from jazz.net/ns.

**Comment by jamsden** [comment]
there's no overlap in properties

**Comment by berezovskyi** [comment]
I see, thanks
