### ISSUE TITLE
Address inconsistencies in use of dcterms:title vs. rdfs:label

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#34]
The guideline is to use rdfs:label for the 'display name' property of RDF classes and RDF properties, and to use dcterms:title for the 'display name' property of individual instances of RDF resources. For an RDF individual that is a singleton defined in a vocabulary, we are not 100% consistent. The guidance to use dcterms:title for instances would lead one to do that for the singleton instances that are enumeration values, but in the existing OSLC standards, we have used rdfs:label for most of those - effectively modifying the guidance to be "use rdfs:label for the 'display name' property of all RDF vocabulary terms (RDF classes, properties, and individuals), and use dcterms:title for the 'display name' property of individual instances of RDF resources outside vocabularies."

There is at least one instance of us not following this modified guidance - the example of an extended severity enum value in the Change Management vocabulary at oslc-core/specs/cm/change-mgt-vocab.html.

**Comment by berezovskyi** [comment]
Thanks for bringing this up, Nick! I would have an rdfs label on just about everything. Could you please point me to the original guideline, please?

If we have a requirement with dcterms:identifier "REQ-934" and dcterms:title "rdd labels shall be used consistently", I would generate an rdfs label "Requirement REQ-934: rdd labels shall be used consistently".

--
/Andrew
(from phone)



On Wed, May 29, 2019 at 12:11 AM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


The guideline is to use rdfs:label for the 'display name' property of RDF classes and RDF properties, and to use dcterms:title for the 'display name' property of individual instances of RDF resources. For an RDF individual that is a singleton defined in a vocabulary, we are not 100% consistent. The guidance to use dcterms:title for instances would lead one to do that for the singleton instances that are enumeration values, but in the existing OSLC standards, we have used rdfs:label for most of those - effectively modifying the guidance to be "use rdfs:label for the 'display name' property of all RDF vocabulary terms (RDF classes, properties, and individuals), and use dcterms:title for the 'display name' property of individual instances of RDF resources outside vocabularies."

There is at least one instance of us not following this modified guidance - the example of an extended severity enum value in the Change Management vocabulary at oslc-core/specs/cm/change-mgt-vocab.html.

**Comment by ndjc** [comment]
The original guidance was provided by Arthur Ryman, and was probably in a note on the old open-services.net wiki somewhere. It was also written up as a jazz.net best practice [When to Use rdfs:label Versus dcterms:title](https://jazz.net/wiki/bin/view/LinkedData/UseOfRdfsLabelVersusDctermsTitle).

**Comment by ndjc** [comment]
I would prefer to avoid duplicating properties - especially ones with string values, as that can greatly increase the size of indexes. It might have been a good idea for dcterms:title to be a subproperty of rdfs:label, as mentioned elsewhere on the internet (https://lists.w3.org/Archives/Public/public-gld-wg/2013Mar/0109.html).

**Comment by ndjc** [comment]
Closed by mistake.

**Comment by berezovskyi** [comment]
> It might have been a good idea for dcterms:title to be a subproperty of rdfs:label

Makes sense actually

> When to Use rdfs:label Versus dcterms:title.

I think I understand the motivation but I don't agree with the following reasoning: _rdfs:label is part of the RDF Schema vocabulary and SHOULD therefore be used in vocabulary documents_. Okay, `rdfs:label` is defined in RDFS. This however, does not mean that its usage is restricted to vocabularies. However, it is the wild west out there and it's up to the API providers and consumers to work around this. From Wikidata:

```
wd:Q2 rdfs:label "Earth"@en ;
	skos:prefLabel "Earth"@en ;
	schema:name "Earth"@en ;
```

From RDFS:

> `rdfs:label` is an instance of `rdf:Property` that may be used to provide a human-readable version of a resource's name.

i.e. ANY RDF resource.

**Comment by berezovskyi** [comment]
I strongly suggest that every RDF resource has `rdfs:label`.

**Comment by jamsden** [comment]
I would prefer we follow the original guidance Nick provided in the issue description. We had similar issues with dcterm:type, rdf:type, etc. The inconsistent usage of these properties created a lot of confusion for data consumers.

**Comment by berezovskyi** [comment]
What I am saying is that the guidance is not observed by virtually anyone outside OSLC community.

> dcterm:type, rdf:type

This is _very different_.

But hey, you wore me down and I can't argue with this any longer. Up to you.

**Comment by ndjc** [comment]
fwiw, in some tools we wrote a SPARQL COALESCE statement to extract the human-readable 'name' of a resource - it went something like this:

... something that bound ?uri to an artifact ...
    optional { ?uri oslc:shortTitle ?shortTitle }
    optional { ?uri dcterms:title ?title }
    optional { ?uri oslc:shortId ?shortId }
    optional { ?uri rdfs:label ?label  }
    BIND(COALESCE(?shortTitle,?title,?shortId,?label) AS ?name)

So the conclusion of the discussions above is to leave the original guidance in place. What shall we then do with the existing example of an extended severity enum value in the Change Management vocabulary at oslc-core/specs/cm/change-mgt-vocab.html? I think in this case the most compatible way forward would be to add both rdfs:label and dcterms:title. While I do not want to have that duplication for every resource, having it for those few singleton resources would not cause any issues.

**Comment by jamsden** [comment]
The guidance doesn't need to change.

**Comment by ndjc** [comment]
To be clear, we agreed that nothing in Core needs to change, that we will follow the guidance as modified, and that Nick will raise an issue to get the CM example fixed.

The guidance is:
 * Use `rdfs:label` for the 'display name' property of all RDF vocabulary terms (RDF classes, properties, and individuals). 
 * Use `dcterms:title` for the 'display name' property of individual instances of RDF resources outside vocabularies.

**Comment by ndjc** [comment]
The new issue for CM is issue #365.
