### ISSUE TITLE
Ensure correct spec HTML code 

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#342]
See https://app.circleci.com/pipelines/github/oslc-op/oslc-specs/389/workflows/03e08d5d-da5d-4622-8cbb-b09ddb8a0a52/jobs/385/parallel-runs/0/steps/0-104

- [ ] AM
- [ ] CM
- [ ] Config
- [ ] Core
- [ ] RM
- [ ] Query

QM was fixed in #341

**Comment by jadelkhoury** [comment]
@berezovskyi Is it correct to add to the RM milestone then?

**Comment by berezovskyi** [comment]
Yes!

**Comment by jadelkhoury** [comment]
Run both prettier and the new W3C check

**Comment by jadelkhoury** [comment]
done part of the built script.
closing
