### ISSUE TITLE
RM V2.1 PS01 - respec error in Vocab part

### ISSUE THREAD

**Issue by jadelkhoury** [oslc-op/oslc-specs#350]
I get error message "A conformance paragraph or table is required for your type of document."
How to fix

**Comment by ndjc** [comment]
Since a vocabulary does not normally contain explicit conformance clauses that ReSpec will collect into a conformance table, you must add a suitable paragraph for yourself. This is what I added to Configuration Management just after the intro and before the section including the ReSpec-generated vocabulary:

```
<section id='conformance'>
<h2>Conformance</h2>
<p>Configuration Management servers MUST use the vocabulary terms defined here where required,
and with the meanings defined here.</p>
<p>Configuration Management servers MAY augment this vocabulary with additional classes, properties,
and individuals. In particular, Configuration Management servers MAY define additional types of
configuration, but all configurations MUST also be of one of the types defined here.</p>
</section>
```

**Comment by berezovskyi** [comment]
No need to fix this one. That’s the only thing which is OK and only on the vocabulary page.

--
Cheers,
Andrew

________________________________

**Comment by berezovskyi** [comment]
This one is also good. Shall I adopt it on QM too?

--
Cheers,
Andrew

________________________________

**Comment by jadelkhoury** [comment]
@berezovskyi  You have 2 conflicting messages above.
I think it is good to adopt @ndjc proposal.

**Comment by jadelkhoury** [comment]
@ndjc! I don't seem to find your suggested solution under the config specs.
I looked in all documents under "specs/Config" with no luck.

**Comment by jadelkhoury** [comment]
See https://github.com/oslc-op/oslc-specs/blob/b-config-mgmt/specs/config/config-vocab.html
