### ISSUE TITLE
ReSpec requires that all vocabulary terms have an rdf:type

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#36]
As far as normal RDF vocabulary processing is concerned, a vocabulary term that does not have a type of rdfs:Class or rdf:Property is presumed to be an RDF individual. However, ReSpec does not process things that way, and cannot easily be fixed. So, to get ReSpec to produce entries for your RDF individuals in your vocabs, you **must** add an explicit type. Use the type rdfs:Resource for RDF individuals.

ShapeChecker has been updated to warn about any vocabulary terms without an explicit type; we should rerun ShapeChecker on all existing standards and drafts.

**Comment by berezovskyi** [comment]
Great, thank you! How do we run it from the command line? I will add this to the CI config.

--
/Andrew
(from phone)



On Wed, May 29, 2019 at 12:20 AM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as normal RDF vocabulary processing is concerned, a vocabulary term that does not have a type of rdfs:Class or rdf:Property is presumed to be an RDF individual. However, ReSpec does not process things that way, and cannot easily be fixed. So, to get ReSpec to produce entries for your RDF individuals in your vocabs, you must add an explicit type. Use the type rdfs:Resource for RDF individuals.

ShapeChecker has been updated to warn about any vocabulary terms without an explicit type; we should rerun ShapeChecker on all existing standards and drafts.

**Comment by ndjc** [comment]
Andrew has set up CI for ShapeChecker. This issue will not be fixed.
