### ISSUE TITLE
Identifying OSLC allowed value resources

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#364]
Currently, an OSLC resource shape can define an OSLC property that represents an enumeration. The OSLC property can either use one or more `oslc:allowedValue` to directly reference the members of the enumeration, or reference `oslc:allowedValues`, a resource that may contain zero, one, or many `oslc:allowedValue` statements.

The issue we were trying to address in Jazz Reporting Services was how to identify enumeration values during processing of the RDF graph that contained such enumeration members. Currently, this is very difficult. The resource referenced by `oslc:allowedValue` can be in any RDF graph, and there is no reliable way to identify that resource is an enumeration value at the time you are processing that RDF graph.

One possible solution to this would be to require that all resources referenced by `oslc:allowedValue` to have some marker RDF type (e.g. oslc:AllowedValue).

**Comment by ndjc** [comment]
For enumerations identified by URI values (as is our best practice), I would recommend that each value of the enumerated set be of the same type - an rdfs:class defined specifically for that enumeration. The property with that enum value could then use the class as its oslc:range (or even rdfs:range if the shape wanted the stronger semantics). A tool such as JRS could see a type was used as a range, and that the same property used `allowedValue` or `allowedValues`, deduce that the property was an enumeration, and query for all individuals of that type to get the set of enum values.

I can image use cases for `allowedValue` where the allowed values were not a special purpose enumeration, but just a set of specific resources, ones that the owner of the shape did not own or control, so requiring those resources to have any specific property would not work. For example, suppose I invent a tool that linked to work items, and wanted a property that defined the acceptable set of work item types - then the shape for that property might want the following allowed values:

```
:targetType a oslc:Property ;
    ...
    oslc:allowedValue oslc_cm:Defect, oslc:cm_Enhancement, cm_tool:PlanItem .
```

It is not reasonable to require that the owners of the resources `oslc_cm:Defect`, `oslc:cm_Enhancement`, and `cm_tool:PlanItem` add the oslc:allowedValue marker - those resources were not originally created for that purpose, and are not modifiable by my new tool.

**Comment by DavidJHoney** [comment]
The problem with the suggestion that an enumeration value use rdfs:class and that an OSLC property use oslc:range is that the former and the latter are likely to be in different RDF graphs. At the time you are processing the RDF graph containing the enumeration value, there is no guarantee that the RDF graph containing the OSLC property  exists, or that graph is up-to-date in an indexing provider such as LQE. It's this disconnect between enumeration values and references to them that makes determining that a resource is an enumeration value very difficult.

**Comment by berezovskyi** [comment]
Please decide on a proposed resolution, we intend to move Core PS02 to publication 2 weeks from now if the IETF submission is a success.

**Comment by ndjc** [comment]
Given the difficulties in imposing any acceptable solution that works with predicting that some random resource might be marked as an allowed value of some other resource at some future time, I recommend OSLC take no action - close this issue with no plan to fix.

**Comment by berezovskyi** [comment]
Thank you Nick and David!
