### ISSUE TITLE
Add rdfs:label to example severity enum value in OSLC Change Management spec

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#365]
Per group discussion and issue #34, we have agree to use `rdfs:label` for the 'display name' property of all RDF vocabulary terms (RDF classes, properties, and individuals), and use `dcterms:title` for the 'display name' property of individual instances of RDF resources outside vocabularies.

In change-mgt-vocab.html in the CM spec, there is an example of adding a severity enum value. The example goes:

```
<http://example.com/bugs/2314>
    a oslc_cm:Defect ;
    dcterms:identifier "00002314" ;
    oslc:shortTitle "Bug 2314" ;
    dcterms:title "Invalid installation instructions" ;
    oslc_cm:priority oslc_cm:High ;
    oslc_cm:severity <http://example.com/enums#S1> .

<http://example.com/enums#HOT>
    a oslc_cm:Severity;
    dcterms:title "Severe - HOT" ;
    skos:narrower oslc_cm:Critical ;
    ex:icon <http://example.com/severity/S1.gif> .
```

The `HOT` term should define `rdfs:label`, as well as or instead of `dcterms:title`:

```
<http://example.com/enums#HOT>
    a oslc_cm:Severity;
    rdfs:label "Severe - HOT" ;
    skos:narrower oslc_cm:Critical ;
    ex:icon <http://example.com/severity/S1.gif> .
```

or possibly and redundantly:

```
<http://example.com/enums#HOT>
    a oslc_cm:Severity;
    rdfs:label "Severe - HOT" ;
    dcterms:title "Severe - HOT" ;
    skos:narrower oslc_cm:Critical ;
    ex:icon <http://example.com/severity/S1.gif> .
```

I don't really like the latter as it leaves the string defined twice with the potential for the two values getting out of step.

**Comment by jamsden** [comment]
For the example I will just use rdfs:label.

**Comment by jamsden** [comment]
Resolved by https://github.com/oslc-op/oslc-specs/pull/360
