### ISSUE TITLE
Recommendations on URI patterns for published shapes should include fragments

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#376]
In section 4.1 Resource Constraints, the Core 3.0 specs currently recommends the following URI pattern for publishing resource shapes:
```
 http://open-services.net/ns/[vocab short name]/shapes/[version]/[shape-name]
```
It should be 
```
 http://open-services.net/ns/[vocab-short-name]/shapes/[version]#[shape-name]
```
This impacts the metadata and specification references.

**Comment by berezovskyi** [comment]
@jamsden is this a CM ticket or a Core ticket?

**Comment by jamsden** [comment]
I think I only added to CM to not forget it when working on CM. This should not block CM.

**Comment by berezovskyi** [comment]
Closed as fixed in CM PS 01
