### ISSUE TITLE
RM Turtle errors

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#386]
> Checked vocabulary http://open-services.net/ns/rm# from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/rm/requirements-management-vocab.ttl, with 3 issues (0 info, 0 warnings, 3 errors)
>    While examining ontology http://open-services.net/ns/rm#:
>       Error on http://purl.org/dc/terms/isPartOf: The named property should be specified for this resource.
>       Error on http://purl.org/dc/terms/hasVersion: The named property should be specified for this resource.
>       Error on http://purl.org/dc/terms/license: The named property should be specified for this resource.
> 
> Checked shapes from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/rm/requirements-management-shapes.ttl, with 1 issue (0 info, 0 warnings, 1 errors)
>    Error on file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/rm/requirements-management-shapes.ttl: This specification requires a ResourceShapesConstraints resource with appropriate metadata.

**Comment by jadelkhoury** [comment]
@berezovskyi Can you please clarify. 
requirements-management-vocab.ttl does not contain any of the 3 properties you mention above: isPArtof, hasVersion, license.

equirements-management-shapes.ttl: I don't even understand what the error message is trying to say.
