### ISSUE TITLE
Add SCVocabulary.ttl generator

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#39]
SCVocabulary.ttl is generated from ResultModel's annotations. Nick has the source code.

**Comment by berezovskyi** [comment]
**NB!** Enable annotation processing in the Gradle config: https://github.com/oslc-op/oslc-specs/blob/master/tools/ShapeChecker/.factorypath

**Comment by ndjc** [comment]
Done. However, further changes will be needed to work with the Gradle build.
