### ISSUE TITLE
QM spec fails W3C HTML validation

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#390]
[(X)HTML5 validation results for quality-management-spec.html.pdf](https://github.com/oslc-op/oslc-specs/files/5009166/X.HTML5.validation.results.for.quality-management-spec.html.pdf)

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden I have updated the checklist on wiki to include those checks too, please check Core and RM.

**Comment by jadelkhoury** [comment]
@berezovskyi  What exactly are you referring to? 
I don't see anything specifically new under https://github.com/oslc-op/oslc-specs/wiki/Publication-guidelines

**Comment by berezovskyi** [comment]
- [ ] Ensure no HTML errors are present in the spec draft (check via [W3C](https://validator.w3.org/nu/)) and also in the saved snapshot of every part of the spec (check via File Upload option of the W3C checker)

from the updated checklist
