### ISSUE TITLE
QM & RM: Should the "Name" in the Shapes description be referencing the shape or the vocab term?

### ISSUE THREAD

**Issue by jadelkhoury** [oslc-op/oslc-specs#397]
![image](https://user-images.githubusercontent.com/7108694/89526118-8eb70e00-d7e7-11ea-8d25-8b437c2603ba.png)

**Comment by berezovskyi** [comment]
Proposal:

- remove _Name_
- rename _Type URI_ to _Describes_

**Comment by ndjc** [comment]
ReSpec 2.1.18 has now been published on master to fix this issue as agreed.
