### ISSUE TITLE
Should all headers referenced in OSLC specs be written in lower case?

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#411]
HTTP headers are _case-insensitive_ in HTTP/1 [RFC7230], and *MUST* be encoded in _lower case_ for HTTP/2 [RFC7540].

I have mentioned this in the Configuration Management draft while discussing the configuration context header, and while doing that, I have updated all the Configuration Management references and examples to show all headers in lower case (configuration-context, prefer, location, etc.)

Should other specs do the same?

**Comment by berezovskyi** [comment]
The key part is that the headers must be lowercased before encoding. As such, I consider it to be the job of an HTTP/2 client to lowercase the headers. See https://tools.ietf.org/html/rfc7540#section-8.1.2 for examples, where 'ETag' header is supplied in that exact form and is lowercased in the HTTP/2 request. I don't think any action is necessary here unless we are claiming to show HTTP/2 request headers. I don't think we want to do that either as HTTP/2 header illustration looks more busy and adds no value (HTTP/1.1 on the left, HTTP/2 on the right; taken from RFC 7540 linked above):

```
     GET /resource HTTP/1.1           HEADERS
     Host: example.org          ==>     + END_STREAM
     Accept: image/jpeg                 + END_HEADERS
                                          :method = GET
                                          :scheme = https
                                          :path = /resource
                                          host = example.org
                                          accept = image/jpeg
```

**Comment by berezovskyi** [comment]
Please reopen this if you think the issue needs further discussion. I assume we keep `Configuration-Context` and HTTP/1.1 style of the request examples.
