### ISSUE TITLE
Change Management spec should be more clear that oslc_cm:status is deprecated

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#412]
The vocabulary for Change Management 3.0 declares that `oslc_cm:status` has `vs:term_status "archaic"` -  that is, the term is deprecated. However, the document `change-mgt-spec.html` has a long section on "**Status, State and State Predicates**" that does not mention this.

The IBM ELM Reporting product ran into this recently, where they used the `oslc_cm:status` field for a scenario where they should have used the newer `oslc_cm:state` field.

I suggest adding the following to the end of the last paragraph in the "**Status, State and State Predicates**" section:

> The property `oslc_cm:status` is now deprecated; use of `oslc_cm:state` and state predicates is preferred.

**Comment by jamsden** [comment]
I have added that.
