### ISSUE TITLE
Unroll SC CircleCI config

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#418]
Use https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute as for the ShapeChecker checks, as was done for the prettier checks in #417.

**Comment by ndjc** [comment]
<img width="781" alt="Screen Shot 2020-08-27 at 10 49 34 AM" src="https://user-images.githubusercontent.com/4313031/91477416-2d68e480-e853-11ea-993a-2331cef2058d.png">

**Comment by berezovskyi** [comment]
Amazing, thanks!
