### ISSUE TITLE
Section Abstract is not present on Reconciliation Spec

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#42]
The issue to list the problems that I'll find during the reconciliation spec editing process.

**Comment by FabioRNT** [comment]
Section Abstract is not present on (https://archive.open-services.net/wiki/reconciliation/OSLC-Reconciliation-Specification-Version-2.0/index.html)

**Comment by berezovskyi** [comment]
I think it's best to keep one issue per item
