### ISSUE TITLE
Collect Statements of Use (SOU) for OSLC Product Specifications

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#430]
This is required to be able to promote the product specifications from PD to COS on the way to OASIS Standard. Three SOUs are required. The OSLC specs in scope for this issue are:

- [x] OSLC Core 3.0
- [ ] OSLC Query 3.0
- [x] OSLC Requirements Management 2.1
- [x] OSLC Change Management 3.0
- [ ] OSLC Quality Management 2.1

The following companies are candidates for requesting SOUs for the above specifications:

OSLC Sponsors:
* Koneksys
* Accenture
* AIT Austrian Institute of Technology
* Axel Reichwein
* Bank of America 
* Cisco Systems
* Dassault Systemes
* Ericsson Fujitsu Limited 
* IBM 
* KTH Swedish Royal Institute of Technology
* pure-systems GmbH
* Red Hat
* Siemens AG
* Software AG
* The Boeing Company

Companies that have implemented OSLC:
* Honda
* Dassault
* Sodius
* Daimler
* AT&T
* DAF Trucks
* Embraer
* MID Smartfacts
* PTC
* Rabobank
* SBE Vision
* Scania
* Schaeffler
* Tasktop
* TechRev

Here's a possible template for sending out requests to submit SOUs:

The {specificationIdentifier} represents a milestone in the standardization process for open-services.net specifications. This revision incorporates the insight gained from many implementations, integrations with other lifecycle management tools, and user experience, while maintaining compatibility with open-services.net OSLC specification. Implementations of these earlier OSLC specifications are therefore applicable for Statements of Use for {specificationIdentifier}.

The OASIS OSLC Open Project is ready to accept Statements of Use from implementers. This is an essential part of the OASIS standardization process and will enable us to progress from Project Specification (PS) to Candidate OASIS Standard (COS) and eventually to OASIS Standard. Please see [Section 14. OASIS Standard Approval and External Submissions of the TC process](https://www.oasis-open.org/policies-guidelines/open-projects-process#oasis-standard-approval-external-submissions) for more information. In summary:

> "[Statement of Use](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22#dStatementUse)",  with respect to a Committee Specification or Project Specification, is a written statement that a party has successfully used or implemented that specification in accordance with all or some of its conformance clauses, identifying those clauses that apply, and stating whether its use included the interoperation of multiple independent implementations. The Statement of Use must be made to a specific version of the Specification and must include the Specification's approval date. The party may be an OASIS Member or a non-member. In case of a non-member, the Statement of Use must be submitted via the Technical Committee's or Project Governing Board's comment facility. A TC or PGB may require a Statement of Use to include hyperlinks to documents, files or demonstration transcripts that enable the committee's members to evaluate the implementation or usage. A Statement of Use submitted to the TC or PGB must be approved by TC Resolution or PGB action as an acceptable Statement of Use with respect to the Specification. A party can only issue one Statement of Use for a given specification. When issued by an OASIS Organizational Member, a Statement of Use must be endorsed by the Organizational Member's Primary Representative.

Statements of Use must be endorsed by the OASIS Organizational Member's Primary Representative. Submitters just need to notify the Technical Committee, by submitting their 'Statement of Use' to the oslc-op@lists.oasis-open-projects.org mailing list. A typical statement of use could be:

> {insert name / org here} has successfully implemented the {specificationIdentifier} ({specificationURL) dated {projectSpecificationRevisionDate}, in accordance with the conformance clauses defined in Section "Conformance" of the specification. This use of the specification includes interoperation with other similar independent implementations, as well as integration with tools supporting other OSLC domain specifications.

**Comment by berezovskyi** [comment]
I opened #477 for the QM. I suggest we close this issue and open another one for Query. Hard to put this issue under a milestone.

_I will close issues from now on as a default action to attempt a clean-up. Please reopen if you disagree and think this issue shall remain open._
