### ISSUE TITLE
Support more scalable and performant discovery

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#437]
**Use case 1**
An ELM application has 1000 project areas. An OSLC client wants to create a resource of type T using the creation factory for a known project area PA.

**Why the current discovery process does not scale well**
The SPC will have references to at least 1000 service providers. For scalability, these will not be embedded in the same RDF graph. So the client has to:

1. GET the SPC.
2. GET each of the 1000 service providers, looking for one whose `oslc:details` references project area PA.
3. Once the service provider is found, iterate through the services (no additional GETs required) looking for a service that declares a creation factory for T.

It's (2) that does not scale well. Some applications overcome this by caching the data from (2) with some expiry time. Expiry of data is required because new project areas might be created, or existing project areas might be archived.

What's needed is a way to answer such use cases with a small number of GETs (perhaps as few as 2) that does not depend on the number of project areas, service providers or services.

**Why can't an application already declare a query capability for a creation factory?**
It can. But by itself, it doesn't help solve the problem. Currently you can only declare a query capability in a service, referenced by a service provider. But in the graph of the SPC, you have no idea which of the referenced 1000 service providers is one that might contain a query capability for, say, oslc:CreationFactory. So you still may need 1001 GETs.

**Use case 2**
An ELM application has 1000 project areas. An OSLC client wants to display a dialog in which the user first selects a project area, and then shows a selection dialog for type T for the selected project area.

**Why the current discovery process does not scale well**
The SPC will have references to at least 1000 service providers. For scalability, these will not be embedded in the same RDF graph. So the client has to:

1. GET the SPC.
2. GET each of the 1000 service providers. A common convention in Jazz applications is for the name of the service provider to be the name of the project area with which it is associated.

**Proposal**
The specification should encourage implementations to make `oslc:ServiceProviderCatalog` also (has additional RDF type) an `oslc:ServiceProvider`, and that it declare at least one `oslc:Service` that has at least one `oslc:QueryCapability` for querying `oslc:ServiceProvider`. It may also have a query capability for each of `oslc:CreationFactory`, `oslc:QueryCapability`, and `oslc:SelectionDialog`, but see later comments on why this may not always be a useful pattern.

This proposal does not require any shape or vocabulary changes. The proposed change is to recommend and describe a specific pattern that servers may provide to support more scalable and performant discovery, and to provide some examples of the pattern's usage.

A client can determine if it can use this new discovery pattern but testing whether the service provider catalog is also a `oslc:ServiceProvider`, and if so, whether it declares a service that declares the query capability of interest. Older clients would not be impacted. Newer clients, on finding this pattern is supported, can use the query capability for discovery, or if absent, fall-back to the previous discovery algorithm.

One preferred pattern would be a query capability on service providers that may be used to find creation factories, query capabilities, and selection dialogs. In IBM Jazz applications, a common implementation idiom is to have an OSLC service provider for each project area, where the service provider's `oslc:details` references the URI of the project area. 

**Use case 1**
The creation factory for a specified project area area can now be discovered using 2 GETs rather than 1001 GETs:

1. The GET of the service provider catalog provides a response that also states it is a service provider that has a service that has a query capability for `oslc:ServiceProvider`.
2. A GET on the query base with `oslc.where` parameter with the encoding of  `oslc:details=<projectAreaUri> and oslc:service{oslc:creationFactory{oslc:resourceType=<_typeOfT_>}}` and `oslc.select` parameter with the encoding of `oslc:service{oslc:creationFactory *}` should return a query container with just one member service provider, that includes the URIs of all of the creation factories and their properties. A client can then determine which creation factory, of potentially several, represents the one for resource type T.

One might think it would be easier for a client to use a query capability for a `oslc:CreationFactory` directly. The problem is that the project area is referenced by the service provider and not by the creation factory, and there is no property of a creation factory that references its service provider. So while such a query capability could find all the creation factories, it would be impossible to specify data that allowed a client to determine which service provider or project area each referenced member in the query results container represented.

**Use case 2**
The project areas that support a selection dialog for type T can now be discovered using 2 GETs:

1. The GET of the service provider catalog provides a response that also states it is a service provider that has a service that has a query capability for `oslc:ServiceProvider`.
2. A GET on the query base with `oslc.where` parameter with the encoding of  `oslc:service{oslc:selectionDialog{oslc:resourceType=<_typeOfT_>}}` and `oslc.select` parameter with the encoding of `dcterms:title,oslc:details` should return a query container with a member for each service provider along with its name (typically the name of the project area), and the URI of the service provider.

When a user selects a specific project area, the client already knows the URI of the corresponding service provider, and a GET of it allows the client to discover the selection dialog details for type T. Alternatively, the query's `oslc.select` could include details of all selection dialogs which the client could parse to determine the selection dialog details.

**Comment by berezovskyi** [comment]
See https://forum.open-services.net/t/getting-the-title-and-uri-both-for-service-provider-catalog/422/3 as well.

**Comment by berezovskyi** [comment]
If we are going to consider tech changes, we shall consider GraphQL or https://linkeddatafragments.org/concept/ first (would be better to keep it OSLC-based).

**Comment by ndjc** [comment]
+1. I like the proposal as now written.
I would vote to defer any completely different or new approach such as GraphQL or https://linkeddatafragments.org/concept/.

**Comment by berezovskyi** [comment]
@DavidJHoney @jamsden I really want to include this enhancement. We have little time in Core. Can we put it in the Query spec instead? Or at least

> make oslc:ServiceProviderCatalog also (has additional RDF type) an oslc:ServiceProvider,

in the Core and the put the rest in the query spec?

**Comment by DavidJHoney** [comment]
Most of this really belongs in the discovery part of OSLC Core. While it leverages OSLC Query, thje use patterns are specific to discovery. As I commented elsewhere, our primary goal should be to get OSLC Core to public OASIS standard. There is nothing preventing us from addressing this issue in a CSD 3.1 later PSD 3.1. This issue is one of many that could easily become excuses for delaying our primary goal.

**Comment by berezovskyi** [comment]
Closed deferred

**Comment by DavidJHoney** [comment]
I think we should keep this issue open as a reminder to tackle in 3.1.

**Comment by berezovskyi** [comment]
We will go over all closed issues with a tag "Status: Deferred" once a COS/OS is published. I want to work down to 0 issues open for the OS. Github tracker is very limited in its capabilities and even 100 tickets are hard for me to navigate, e.g. because there is no priority sort. Also, 0 is a pleasant number to work towards :)

**Comment by DavidJHoney** [comment]
One thing we might want to consider is adding an `oslc:serviceProvider` statement in creation factory, selection dialog, creation dialog, and query capability. This would then support a query on nested properties, and hence we might support more useful query patterns. For example, a GET on the query base of a query capability for querying creation factories with oslc.where parameter with the encoding of `oslc:serviceProvider{oslc:details=<projectAreaUri>} and oslc:resourceType=<_typeOfT_>}`.
This would be a more direct query pattern and easier for a client to consume.  Without the `oslc:serviceProvider` statement, a query capability for a creation factory cannot query for the project area because that is not a nested property. This _would_ require a minor change to OSLC Core, but one I think we should consider.
