### ISSUE TITLE
Write a Configuration Management Primer

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#444]
## Intro

The idea is to prepare it as an OP note following RDF primer/spec example. Initially suggested by @jadelkhoury.

## References

- @ndjc's initial link: https://jazz.net/gc/doc/scenarios
- https://www.w3.org/TR/rdf11-primer/
- https://open-services.net/resources/oslc-primer/

---

CC @img @DavidJHoney

**Comment by berezovskyi** [comment]
asked Chet for the ability to publish an OP Note. Otherwise this will be done as a spec PSD or even an open-services post similar to other OSLC primers.

**Comment by berezovskyi** [comment]
During the call, we were debating how much CCM expertise do we expect. I am leaning towards nearly 0.  I expect the implementer of the CCM spec have OSLC experience, maybe building simple OSLC servers with LyoD or plaing with the reference implementation and some change management / release engineering experience / PLM experience but not much beyond that. If you see RDF primer, they do not expect you to come having a fresh knowledge of the First Order Logic and Description Logic. I recall that during both OSLCfests we had people with extensive PDM/PLM expertise who could not understand CCM and CCM spec despite being one of our target groups.

@ndjc and others: I would also appreaciate if you have CCM 101 links that could get me up to speed in under 3-4 hours of effort (to some degree, of course).

**Comment by ndjc** [comment]
This is already covered by issue 186. Andrew, you should copy your comments to that existing issue.

**Comment by jamsden** [comment]
We had talked about how OSLC config management related to the PLM view. We could also relate it to git/GitHub and EWM SCM. By showing how these different views on versioning and configuration management relate, we can leverage experience people may already have.

**Comment by chet-ensign** [comment]
@berezovskyi - I don't see any reason not to produce a Product Note similar to a Committee Note. Would you like us to put together a template you can model from?
