### ISSUE TITLE
Add CSP reference to the Delegated UI section

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#458]
During the meeting, I expressed my concern that Jazz, Polarion, and Lyo all failed to include even a single CSP/CORS header (let alone get the cookies right). I think we should reference https://www.w3.org/TR/CSP/ in the Core to say that one shall follow it to get the IFRAMEs working for the delegated UIs correctly.

Jim argued that things move too fast in that area. I strongly disagree because:

1. A standard is a standard is a standard. CSP is a W3C CR, which is equivalent to OASIS COS. I can understand caution of referring to https://fetch.spec.whatwg.org/#http-cors-protocol but the CSP can be made a normative reference. Just because our standard moves too slow does not mean we shall ignore everything else that is moving a bit faster.
1. Neither https://tools.ietf.org/html/rfc7540 nor https://quicwg.org/base-drafts/draft-ietf-quic-http.html stopped us from adding a normative reference to HTTP/1.1 in the specs.

Let me put it this way: since Feb 2020 (https://blog.chromium.org/2019/10/developers-get-ready-for-new.html), you **cannot** show an OSLC Delegated UI in an IFRAME (unless someone has another secret method I am not aware of) in ANY modern browser unless the server follows https://www.w3.org/TR/CSP/.

You **cannot** also get an OSLC Client to run in a browser without following https://quicwg.org/base-drafts/draft-ietf-quic-http.html. The proof of this misery is the fact that every OSLC request made in a Jazz app is made through a "proxy", e.g. `https://nordic.clm.ibmcloud.com/qm/proxy?uri=https%3A%2F%2Fgit.md.kth.se%2Fpolarion%2Foslc%2Fservices%2Fcatalog`.

Unless you follow https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#section-5.2, a user **cannot** log in to the app via a Delegated UI dialog in 2020.

We MUST write in the OSLC spec that implementers should follow those **standards** if they want their Delegated UIs to work. Or maybe we don't like that amending the spec would allow to officially™ pronounce `/proxy?uri=%the_real_uri_you_should_have_been_making_a_request_to` to be a miserable  kludge (that we also have in Lyo, btw).

I feel that people who are advocating against this are having some dual understanding of what a standard or a spec is (I do, however, agree that https://fetch.spec.whatwg.org/#http-cors-protocol is bad and I am against "living" standards) or have simply never cared to even open those specs and thinking that it's all "magic". I guess I now understand why some of our users may think this way about OSLC.

**Comment by berezovskyi** [comment]
Request For Comments from @ndjc @jamsden @jadelkhoury and all @oslc-op/maintainers.

**Comment by jamsden** [comment]
Agree that some guidance here is needed in the core, or discovery specs. Andrew, as you understand this, do you want to propose something? If its SHOULD, and reflects our understanding of current standards and practices, then we can avoid having to created substantive changes that would requires a new PS revision. 

But we're getting close to the wire re: COS and public review of these OP specs. We have to draw the line on what's good enough or we'll never get them done.

**Comment by berezovskyi** [comment]
Yes, a small amendment to a section with a few SHOULDs should have the minimal impact. I will draft something for you to scrutinise further.

1. I think that referencing https://www.w3.org/TR/CSP/ in DUI section should be fine.
2. https://fetch.spec.whatwg.org/#http-cors-protocol may not be appropriate to reference given its "living" (or "bleeding edge", as programmers usually call it) status and it's not exactly a thing needed for IFRAMES but rather for loading resources across domains. So, essentially what https://github.com/OSLC/oslc-browser needs from servers. Maybe we can park it given that there is no proper thing to reference but just say something vague along the lines of "ensure requests to the OSLC resources can be made across domain boundaries."
3. Sadly, https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#section-5.2 which actually defines what cross-site actually means, is also a draft. I also would rather not reference https://tools.ietf.org/html/rfc6265 if it's about to be obsoleted soon (it also does not contain a standard definion what is cross-site and what is same-site). Further, the specific breaking change is specified in https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.2 which is also a draft.

**Comment by berezovskyi** [comment]
Well, I just decided to take https://github.com/OSLC/oslc-browser#using-the-oslc-server-university-example for a spin and the first thing it says it so disable CORS in the browser 😭  But OK.

> I will keep this thread to collect all things needed to get OSLC Clients and DUIs to work across domains (what's integration otherwise?).

One thing it requires (obviously, I am not planning to restart Chrome with a flag to disable all security) is a special whitelist of an OSLC header:

> Access to fetch at 'https://polarion.oslc.itm.kth.se/polarion/oslc/rootservices' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field oslc-core-version is not allowed by Access-Control-Allow-Headers in preflight response.

@jamsden @ndjc have we registered/specified this header properly?

@ndjc can you combine the IANA registration requesst for config header with this one? Better yet, start the process for the `oslc-core-version` first given that the spec is at the PS level and that's enough to satisfy IANA?

**Comment by berezovskyi** [comment]
Also see https://github.com/oslc-op/website-content-negotiation/issues/8

**Comment by berezovskyi** [comment]
Upd: I was wrong, CORS was a full Recommendation on W3C https://www.w3.org/TR/2014/REC-cors-20140116/. Almost nothing changed since 2014 as opposed to the worries I have heard during the call except for the change of the "*" origin semantics _iff_ the credential mode is enabled. Everything else you have been suffering from is the result of web browsers simply enforcing the CORS W3C recommendation more and more every year.

Also, I was wrong that "origin" is only defined in a recent RFC draft: https://tools.ietf.org/html/rfc6454#section-4. We can use this term and refer to the aforementioned RFC.

**Comment by berezovskyi** [comment]
Fixed in #468
