### ISSUE TITLE
Add dcterms:identifier to resource shape for oslc:Error

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#466]
In many implementations, error messages include message identifiers. These identifiers are identical across translated messages across supported locales. A client may wish to test for specific types of error response, and for this  to be robust across locales. Extracting such message identifiers from the oslc:message text is not ideal. It would be better if the message identifier could be represented as a separate property using a standard property. 

Proposal: Add dcterms:identifier as an optional property, with cardinality Zero-or-one, to represent such a message identifier.

Note the proposed cardinality is intentionally not Zero-or-many. If an oslc:message uses a message identifier, there should be a unique single identifier for it.

**Comment by berezovskyi** [comment]
I am in favour of this. A standard way in RDF would be to use a subclass of oslc:Error instead of an id but we know well that in the OSLC land practical support for RDF multiple inheritance is hard (even though it's good for _data_). I also support Zero-or-one cardinality.

Please submit a PR and I will gladly review.

**Comment by frejfrej** [comment]
I would also suggest adding a "dcterms:description" property. Maybe the need comes from that, implementation wise, it is currently not a subclass of AbstractResource, which prevents any additional property from being used. But I still think it makes sense to provide a way to include an additional message, and dcterms:description seems like a good fit for the need.

Additional proposal: Add dcterms:description as an optional property, with cardinality Zero-or-one, to represent an additional description of the error (such as a stacktrace, a set of logs, etc.)

**Comment by berezovskyi** [comment]
> implementation wise, it is currently not a subclass of AbstractResource, which prevents any additional property from being used

I think this is a defect in Lyo, let's continue in https://github.com/eclipse/lyo/issues/77

> Add dcterms:description

https://github.com/oslc-op/oslc-specs/issues/465 proposes to add `oslc:cause`. I can certainly see it be declared as an RDFS subproperty of `dcterms:description` but that will only help if there is an RDFS/OWL reasoner support in the system.

**Comment by berezovskyi** [comment]
@DavidJHoney please make a PR. We should wrap up Core PS02 within 2 weeks.

**Comment by DavidJHoney** [comment]
The shape already contains dcterms:identifier. Closing this issue.
