### ISSUE TITLE
Add all Root Services properties to SPC shape

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#467]
After Jim said again today that RootSvc was not strictly mandatory for OSLC servers and stubmling across https://github.com/oslc-op/oslc-specs/issues/281, I had a throught: well, maybe we should then just redefine all properties (under our namespace) that implementers put into the RootSvc into the SPC shape?

I want to clearly say: I don't care about use cases where servers put whole SPC behind 401 auth, they can keep using RootSvc. I am thinking of a case where you get a very lean SPC first, authenticate and get a full SPC or simply get a full SPC at the start. Even simpler approach would be to define an open SPC (under well-known, for example) with root service properties and a link to another SPC behind auth (where they are generated today by LyoD).

Rationale: OSLC users cannot even start migrating away from Root Services until there is an alternative. This would provide one.

**Comment by jamsden** [comment]
But that eliminates one of the big value propositions of referencing root services, enabling discovery of discovery for most existing OSLC server implementations.

**Comment by ndjc** [comment]
@berezovskyi  - can you give an example of a property that would be added to the SPC shape under this proposal?

**Comment by berezovskyi** [comment]
@ndjc JFS OAuth is the first candidate https://github.com/oslc-op/refimpl/blob/master/src/server-rm/src/main/java/co/oslc/refimpl/rm/gen/services/RootServicesService.java

@jamsden no, OSLC is an integration technology and we will simply provide two approaches, with one being a bit better than another. The old approach has legacy value on its own while the new method can gain any adoption.

**Comment by berezovskyi** [comment]
@jamsden this will actually be a third way to discover oauth (v2 at least), the canonical being the `/.well-known/openid-configuration` resource https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

**Comment by berezovskyi** [comment]
I will defer this until 3.1
