### ISSUE TITLE
Update: Typographical Conventions and Use of RFC Terms

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#470]
OSLC-OP should update the "Typographical Conventions and Use of RFC Terms" sections to use the current IETF format, which includes another RFC (8174) and reference to the specific BCP 14, along with the traditional 2119. It also adds "NOT RECOMMENDED" to the terms list. This should also be applied for other future OSLC-OP publications.

Text:
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

Citations:
[RFC2119]
Bradner, S., "Key words for use in RFCs to Indicate Requirement Levels", BCP 14, RFC 2119, DOI 10.17487/RFC2119, March 1997, http://www.rfc-editor.org/info/rfc2119.

[RFC8174]
Leiba, B., "Ambiguity of Uppercase vs Lowercase in RFC 2119 Key Words", BCP 14, RFC 8174, DOI 10.17487/RFC8174, May 2017, http://www.rfc-editor.org/info/rfc8174.

**Comment by ndjc** [comment]
ReSpec issue 44 (https://github.com/oasis-tcs/tab-respec/issues/44) fixes at least part of this requirement. All OSLC OP secs will have to update to use ReSpec 2.1.21 to get this fix, once ReSpec PR 45 (https://github.com/oasis-tcs/tab-respec/pull/45) is merged.
