### ISSUE TITLE
RDF type cardinality for resource shapes and properties

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#473]
In Section 5 of https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/resource-shape.html#resourceShape-shape, the spec describes the resource shapes for `oslc:ResourceShape` and `oslc:Property`. However, the shapes omit `rdf:type`. There are a number of shape consuming applications (such as IBM JRS Report Builder) that require that a resource shape has `rdf:type oslc:ResourceShape` and that a property referenced by a shape has `rdf:type oslc:Property`. I think think this is an omission from the core spec.

Proposal (revised 2021-02-04)

Section 5.1, add a row to the properties table as follows:
`rdf:type    Zero-or-Many    true    Resource    Reference    Unspecified    A resource shape SHOULD have at least the rdf:type oslc:ResourceShape.`

Section 5.2, add a row to the properties table as follows:
`rdf:type    Zero-or-Many    true    Resource    Reference    Unspecified    A property SHOULD have at least the rdf:type oslc:Property.`

This would be a non-breaking change, but would achieve the goal of having implementations include the rdf:type.

**Comment by jamsden** [comment]
I don't think ResourceShape is a ResourceShape, it's and rdf:Class, that defines instances of a ResourceShape, it isn't also an instance of a ResourceShape is it? Are we commingling meta-levels?

**Comment by DavidJHoney** [comment]
All the current ELM implementations include the RDF types for resource shapes. The spec actually describes, in the header, the rdf:type. But it's omitted from the list of properties. I think that's an omission. If a server omitted those RDF types, then JRS would not work.

**Comment by jamsden** [comment]
Let's fix this in COS01.

**Comment by jamsden** [comment]
core-shapes.ttl has:
```
:ResourceShapeShape  a       oslc:ResourceShape ;
        oslc:describes       oslc:ResourceShape ;
```
But the type doesn't show up in the ReSpec generated table. So is this already correct?

**Comment by DavidJHoney** [comment]
But does the shape have an oslc:property for rdf:type?
I suspect not. That’s the issue.

**Comment by jamsden** [comment]
No, only oslc:property, oslc:describes, and dcterms:title

**Comment by DavidJHoney** [comment]
That's the issue then. Both need an OSLC property for rdf:type.

**Comment by DavidJHoney** [comment]
FYI, I double checked LQE on jazz.net. All the shapes have rdf:type oslc:ResourceShape. All the properties referenced from the shape by oslc:property have rdf:type oslc:Property (there were 200k+ OSLC properties).

**Comment by jamsden** [comment]
as in the following :type property of an oslc_cm:ChangeRequest:
```
:type  a                       oslc:Property ;
        oslc:name                "type" ;
        oslc:occurs              oslc:Zero-or-many ;
        oslc:propertyDefinition  rdf:type ;
        oslc:representation      oslc:Reference ;
        oslc:valueType           oslc:Resource ;
        dcterms:description      "The resource type URIs, at least one of which should be oslc_cm:ChangeRequest."^^rdf:XMLLiteral .
```

**Comment by jamsden** [comment]
And it should be One-or-many?

**Comment by jamsden** [comment]
All the other resource shapes do have a type property constraint.

**Comment by DavidJHoney** [comment]
Yes. We should not prevent implementations from optionally including additional RDF types.

The description of the OSLC property for rdf:type for resource shape should state that the RDF type must include oslc:ResourceShape.

The description of the OSLC property for rdf:type for property shape should state that the RDF type must include oslc:Property.

**Comment by ndjc** [comment]
+1.

This is in line with other areas of the specs where we used to allow inferred rdf:type values, but now prefer explicit ones. Inferred resource types work well with the normal flow of operations in a specific tool, where that flow may have led to an inferred type, but do not provide the flexibility that might be required when those RDF resources are accessed independently such as in reporting solutions or other integrations.

**Comment by jamsden** [comment]
We need to discuss this at the next oslc_op meeting as this is a potentially breaking change. We're adding a new required property. I think it's OK, because as David points out, that is consistent with common practice and an interpretation of the resource shape 2.0 spec. But it could still be an issue for some OSLC implementations.

**Comment by DavidJHoney** [comment]
Updated proposal in first comment.

**Comment by berezovskyi** [comment]
Alternative proposal from https://github.com/oslc-op/oslc-admin/blob/master/minutes/2021/2021-02-04.md#oslc-shapes:

1. Add `rdf:type` with cardinality `1..*`. `0..*` doesn't make sense as the very application of the shape is done on a type basis. I.e. there is no way for us to even consider shape applicability to a given resource unless we know the type of the resource.
2. Range of `rdf:type` shall be any Resource but the description shall include a MUST clause that one of the types MUST be ResourceShape or Property.

Finally, we can introduce "breaking" changes as in "new MUSTs". What we cannot do is to break the old specs (ie introduce backwards-incompatible breaking changes), changing the meaning of existing MUSTs etc. A shape with an added `rdf:type oslc:ResourceShape` is still a shape and a valid OSLC 2 resource. It's just that there is no coming back once we add this MUST.

**Comment by berezovskyi** [comment]
Also, `dcterms:title` should have a SHOULD clause in the description as it is hard for tools to work with resources without a title.
