### ISSUE TITLE
Make tech aspects of versioning normative

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#475]
As per discussion in https://github.com/oslc-op/oslc-admin/blob/master/minutes/2021/2021-02-04.md#iana-application

**Comment by berezovskyi** [comment]
> OSLC Core 3.0 does not introduce any changes that would break existing OSLC 2.0 clients. Because of this, there is no need for OSLC Core 3.0 to require servers or clients to utilize an OSLC-Core-Version header with a value of 3.0.

I really don't like the wording here. First, we could use NOT RECOMMENDED wording from RFC here.

But then, I am not sure why would we discourage "3.0" value being sent by either side. I think it is a matter of time until we get some initial LDP support on the server side and find out that Jazz TRS client fails to work with it. Defect or no defect, a workaround may be necessary. The most appropriate one would be to return LDP-free response if the client asks for 2.0 explicitly. So, I would at least think of a way to avoid over-reliance on version number but then still leave an escape hatch for real-world workarounds that would rely on the version instead of hardcoding IP addresses or HTTP agents or domain names of the clients to serve them "just right" content.

**Comment by jamsden** [comment]
Probably should be stated as what 3.0 servers should do when encountering OSLC-Core-Version=2.0.

**Comment by berezovskyi** [comment]
Fixed in https://github.com/oslc-op/oslc-specs/commit/99e0be0260228185b9c58160bae87e3c4e9f36be

The text in question changed to:

> OSLC Core 3.0 does not introduce any changes that would break existing OSLC 2.0 clients. Because of this, OSLC Core 3.0 clients and servers may continue to utilize the OSLC-Core-Version header with the value of "2.0". [core-46]
