### ISSUE TITLE
OSLC forum member links are broken on OSLC Reconciliation 2.0 Appendix C

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#48]
Most of the links on the Contributors section are broken, so I couldn't retrieve an organization to attach to the names of the contributors.

**Comment by berezovskyi** [comment]
@jamsden should have a list from OSLC MS regarding the affiliations.

--
/Andrew
(from phone)



On Wed, Jun 12, 2019 at 11:00 PM +0200, "Fábio Ribeiro de Assis Neto" <notifications@github.com<mailto:notifications@github.com>> wrote:


Most of the links on the Contributors section are broken, so I couldn't retrieve an organization to attach to the names of the contributors.
