### ISSUE TITLE
OSLC Core contains local CSS styles

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#49]
Shouldn't all OSLC specs have the same styles? If so, the styles in OSLC Core should either be removed altogether, or merged into the standard ones used by ReSpec.

**Comment by ndjc** [comment]
Other specs may have this same issue - I just checked Core Part 1 because I was using that as a testbed for the latest ReSpec changes.

**Comment by jamsden** [comment]
Agreed, we need to normalize all styles for the Open Project, and they should be all provided by ReSpec except for rare exceptions. All the styles/* files should probably be removed.

**Comment by berezovskyi** [comment]
Do you still intend to keep the root directory with the styles?

--
/Andrew
(from phone)



On Thu, Jun 13, 2019 at 3:27 AM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Agreed, we need to normalize all styles for the Open Project, and they should be all provided by ReSpec except for rare exceptions. All the styles/* files should probably be removed.

**Comment by ndjc** [comment]
I see no need to keep an empty styles directory - given the agreement in this morning's meeting that all those styles should be built-in. I will remove the directory after we have updated the current set of published and in-progress specs. That may leave some currently inactive draft specs with broken links, but that's OK.

**Comment by berezovskyi** [comment]
Sounds good to me, thanks!

--
–Andrew.

Från: Nick Crossley <notifications@github.com>
Svara till: oslc-op/oslc-specs <reply@reply.github.com>
Datum: torsdag, 13 juni 2019, W24 17:10
Till: oslc-op/oslc-specs <oslc-specs@noreply.github.com>
Kopia: Andrii Berezovskyi <andriib@kth.se>, Comment <comment@noreply.github.com>
Ämne: Re: [oslc-op/oslc-specs] OSLC Core contains local CSS styles (#49)


I see no need to keep an empty styles directory - given the agreement in this morning's meeting that all those styles should be built-in. I will remove the directory after we have updated the current set of published and in-progress specs. That may leave some currently inactive draft specs with broken links, but that's OK.

**Comment by ndjc** [comment]
We also agreed that I will merge the oslc-core.html inline styles with the ReSpec built-in ones, and remove them from the Core spec itself.

**Comment by ndjc** [comment]
ReSpec has now been updated to have all the styles that I think it needs, including both the set of files in oslc-specs/styles and the relevant ones from the Core spec source.

**Comment by ndjc** [comment]
ReSpec styles have been updated to include all useful styles previously defined elsewhere in oslc-specs/styles or locally in specs.

All OSLC specs (including those not currently published or active) have been updated to remove local styles that should be common, and to remove references to the files under oslc-specs/styles.

The oslc-specs/styles directory has been removed.

**Comment by berezovskyi** [comment]
Thanks Nick!
