### ISSUE TITLE
Common core property oslc:discussedBy range should be oslc:Discussion, not oslc:Comment

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#50]
And the cardinality should be Zero-or-one.

**Comment by berezovskyi** [comment]
Why the need to restrict it to max one?

--
/Andrew
(from phone)



On Fri, Jun 14, 2019 at 8:22 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


And the cardinality should be Zero-or-one.

**Comment by jamsden** [comment]
The multiplicity is handled in Discussion::comment, not discussedBy property.

**Comment by berezovskyi** [comment]
Those are 2 different properties, I am not sure I follow the reasoning. We can take it during the OP call

**Comment by jamsden** [comment]
Consider these assertion patterns:
oslc_am:Resource oslc:discussedBy oslc:Discussion.
oslc:Discussion oslc:comment oslc:Comment.

oslc:discussedBy has the wrong range in the shape constraints.

**Comment by berezovskyi** [comment]
I agree with the range, not with the cardinality.

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 4:10 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Consider these assertion patterns:
oslc_am:Resource oslc:discussedBy oslc:Discussion.
oslc:Discussion oslc:comment oslc:Comment.

oslc:discussedBy has the wrong range in the shape constraints.

**Comment by jamsden** [comment]
Maybe. Discussion only has two properties, discussionAbout (which is a redundant backlink of Resource::discussedBy), and oslc:comment, zero-or-More oslc:Comment resources, which contain all the data. It's not clear why Discussion is needed at all, and perhaps that's why Core discussedBy range is currently Comment instead of Discussion. But that's what's in OSLC 2.0 and what's implemented in EWM (formerly RTC). Core 2.0 doesn't specify multiplicity for discussedBy, so we should discuss this to see if anyone remembers or is familiar with existing implementations.

**Comment by jamsden** [comment]
Perfect Nick, thanks for the well thought out discussion.

**Comment by jadelkhoury** [comment]
It's a pity standards need to be written in a compact way, so one looses the rational behind many of the decisions presented.

**Comment by ndjc** [comment]
I will add some part of my previous comment to the spec as a non-normative note.

**Comment by jamsden** [comment]
Fixed
