### ISSUE TITLE
oslc_config:Activity, missing shape, should this be in core

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#502]
The configuration management specification defines an oslc_config:Activity but the specification is missing the shape table for it.
I see little about an activity that is specific to configuration management. Many domains might face the same issue about long running operations and the need for a client to poll a server to get the status of a long running operation. The standard HTML idiom is for the response to the request be Accepted with a Location header providing the URI for a resource that a client uses to get the status of the operation. Should we try to standardize on that by moving this to OSLC Core?

**Comment by berezovskyi** [comment]
> Should we try to standardize on that by moving this to OSLC Core?

Maybe! What about Actions spec? Does it have something similar?

**Comment by DavidJHoney** [comment]
While the automation vocabulary defines the terms for state and verdict, it doesn't mention activity. There isn't an automation specification. We decided not to produce one and we would only define some vocabulary terms. So if we define actibity as a resource, we need a specification in which to describe the shape and its usage.

**Comment by berezovskyi** [comment]
CCM: https://oslc-op.github.io/oslc-specs/specs/config/config-resources.html#longoperations

Actions: https://oslc-op.github.io/oslc-specs/specs/actions/actions-spec.html#patterns-final-status does not specify a shape for the `oslc:finalStatusLocation` range; oslc_config:Activity can become one?

Automation puts the activity status directly into the result: https://oslc-op.github.io/oslc-specs/specs/auto/automation-spec.html#h3_Asynchronous-and-Synchronous-Automation-Execution

I generally like the idea to lift `Activity` out of Config spec.

**Comment by ndjc** [comment]
Updated the title and first comment on this issue to reflect the fact that the current draft spec *does* include an Activity shape table (in section 18 on long operations). This was fixed by issue #499 a couple of weeks ago.

**Comment by ndjc** [comment]
Changing the Activity term to be in a different vocabulary is not as easy as it seems. Our tooling has limited (possibly no) support for defining a term that belongs in a different namespace. Changing the namespace would require corresponding changes to a number of implementations (not all of which are necessarily know to us).

**Comment by berezovskyi** [comment]
Deferring till 3.1
