### ISSUE TITLE
RM ReSpec errors

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#51]
The page header does not render correctly: https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-vocab.html (permalink: https://rawcdn.githack.com/oslc-op/oslc-specs/7a6edf9be28d2710ee0b8d2a94676195a9a91d62/specs/rm/requirements-management-vocab.html)

Also https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-spec.html

**Comment by jamsden** [comment]
This is because specStatus is wrong, use specStatus: "PS",

**Comment by jamsden** [comment]
These are changes I'm suppose to do. I've done the CM spec. Looking some feedback and corrections on that. Then I'll update my notes and do the others in a bunch.

**Comment by ndjc** [comment]
And I've fixed the issue in ReSpec that caused it to crash when the spec status was not set.

**Comment by berezovskyi** [comment]
thanks Nick
