### ISSUE TITLE
Bad anchors in AM vocab

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#510]
https://docs.oasis-open-projects.org/oslc-op/am/v3.0/psd01/architecture-management-vocab.html#Resource and https://docs.oasis-open-projects.org/oslc-op/am/v3.0/psd01/architecture-management-vocab.html#LinkType are not resolvable

**Comment by jamsden** [comment]
Fixed, the labels in the vocab ttl file had spaces.
