### ISSUE TITLE
Configuration management component LDPC

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#523]
> Section 3 Component Container
> Configuration Management servers MUST provide a single Linked Data Platform Container ([LDP]) for all components in that server. [config-res-4]
> 
> This component container MUST be advertised as an [OSLCCore3] Creation Factory in the Service resource for the configuration server. [config-res-5]

The intent was to provide a notion of a global LDPC for all containers.
However, there are several things that I find problematic with the above:

1. Scalability: A GET on such an LDPC has to return all the components across all project areas. While a server could support OSLC core paging, servers that do not may have to return a large data response. Clients looking for a specific component would be better served using a query capability where they can specify an `oslc.where` query expression.
2. Usefulness: There is no mechanism to specify which properties of the members, if any, to return, a client. So a server might just return the container and member URIs. That doesn't seem useful to a client that wants to know the names of components because they would have to perform a GET on each of those URIs.
3. Discovery: The only way to discover that LDPC is to discover all the service providers, GET all the service providers to determine which service provider is not specific to a project area. This is the same scalability issue we have as a general issue in OSLC Core.
4. Inconsistency and prescriptiveness: Many Jazz applications provide a service provider per project area, and those service provider provide project area specific creation factories. If a server wants to provide a pan-project-area service provider, it may do so. However, it seems overly prescriptive to require that one be provided just to provide a component LDPC for the entire application. 
5. Compliance: Neither GCM nor EWM SCM is currently not compliant with section 3.

My proposal is to remove all of section 3. Elsewhere in the specification in Section 6 I added:
> A configuration server SHOULD support, and a global configuration server MUST support one or more component creation factories declared in one or more OSLC service providers. [config-res-100]

Clients that want to discover components would be better server by query capabilities. So it might also be appropriate to add:
> A server SHOULD support one or more query capabilities for components.

**Comment by jamsden** [comment]
David, was that section 3 added to support a global configuration - which would seem to have to provide a root container.

**Comment by DavidJHoney** [comment]
I don't know what the motivation was. I suspect our early enthusiam for LDPC may have been part of this, but we've subsequent gone much cooler on this in OSLC spec.

Regardless, GCM did not implement it. GCM supports a component creation factory and query capability for components for each project area specific OSLC service provider. I see little benefit in using LDPCs as a poor-man's query - see my points #1 and #2. Given that currently GCM is the only global configuration provider implementation we know of, it seems odd to include a mandatory requirement that it doesn't implement.

**Comment by DavidJHoney** [comment]
We should also add a section about query capabilities for configurations.

**Comment by DavidJHoney** [comment]
In the OSLC OP meeting 2021-07-22, Jim was ok with removing section 3 but suggested we get Geoff Clemm to review the PSD.
Jim also raised questions about discovering components or configurations, so added two conformance clauses that servers SHOULD support one or more query capabilities for components/configurations.

**Comment by DavidJohnHoney** [comment]
This was removed from the spec.
