### ISSUE TITLE
Config resources - Creation of initial empty baseline might be too prescriptive

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#524]
Configuration Management Part 3: Configuration Specification
Section 9: Creation of Baselines and Streams

> When a new component is created by POSTing to the Component Container, an empty baseline for that component **MUST** be created automatically, and must be added to the oslc_config:configurations container for that component. The empty baseline has no contributions, no selections, and no branch. [config-res-112]

I wonder whether this is too prescriptive. Of the ELM applications, GCM does this, but I don't think ETM, DN, or EWM SCM does this. Is **MUST** too strong here. Perhaps **SHOULD** would be better?

**Comment by jamsden** [comment]
Maybe just providing a consistent head/root for a list/tree?

**Comment by DavidJHoney** [comment]
The motivation was traceability - every stream is derived from a baseline - known starting point. However, Jazz Foundation code does not create such an empty baseline when a stream is first created for a component. Both DN and ETM use that code, so neither implement that. I think we should downgrade the **MUST** to a **SHOULD**.

**Comment by DavidJHoney** [comment]
And EWM SCM which uses it's own implementation, does not do this. So out of the ELM applications, only GCM is compliant. That feedback should tell us the spec is too prescriptive.

**Comment by jamsden** [comment]
Maybe, depends on why foundation and EWM SCM don't do this. We should think about the implications re: integrations, predictability, consistent traversal, etc.

**Comment by DavidJHoney** [comment]
Let's discuss this next meeting. I regard this as an issue that potentially blocks publication of Configuration Management 1.0 as a PSD. There's little point starting with a specification where a significant number of current implementations are not compliant. That's why Nick initiated a compliance review - he wanted to validate the specification prior to publication. I'm simply following the same path now that Nick has retired,

**Comment by DavidJHoney** [comment]
In the OSPC OP meeting 2021-07-22, Jim agreed is was ok to downgrade the MUST to a SHOULD.

**Comment by DavidJohnHoney** [comment]
The spec was updated, so nothing remains to be done on this issue.
