### ISSUE TITLE
Configuration management doesn't support creation of new versions for a change set

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#527]
_OSLC Configuration Management 1.0 Part 3: Configuration Specification_, section _7. Supported Operations on Versioned Resources in a Configuration Context_ says:

> PUT: Update the state of a specified versioned concept resource in a specified stream; this operation may cause the creation of a new version of the resource [config-res-108].

This doesn't cover being able to do so in a change set.

Proposal: Amend that conformance clause as follows:

PUT: Update the state of a specified versioned concept resource in a specified stream or change set; this operation may cause the creation of a new version of the resource [config-res-108].

There are also similar references that need updating:

> POST to a component in the context of a stream, resulting in the creation of the first version of a new concept resource, or a new version of an existing resource. A successful response MUST include a Location header specifying the URI of the newly created resource. [CONFIG-RES-110]
> DELETE: Delete the current mutable version resource in a specified stream.

**Comment by jamsden** [comment]
Agree

**Comment by DavidJohnHoney** [comment]
This was addressed nin the PSD.
