### ISSUE TITLE
Config spec shall add a CORS section

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#533]
Config spec shall add a CORS section to specify that servers SHOULD be configured to whitelist a `Configuration-Context` header so that JS client requests are not blocked when they send a request with this header and responses are not stripped of this header by the browser for security reasons.

**Comment by jamsden** [comment]
That text is in OSLC Core. It should not need to be repeated in the other specs that depend on Core.

**Comment by berezovskyi** [comment]
Please observe that the `Configuration-Context` header is not mentioned in the Core. We need extra statement on whitelisting this particular header if the server implements Config. The rest of the advice will obviously be simply referenced from the Core and not repeated here.

**Comment by berezovskyi** [comment]
Done in PSD01: https://github.com/oslc-op/oslc-specs/blob/config-v1.0-psd01/specs/config/config-resources.html#L339
