### ISSUE TITLE
OSLC Query uses H-tags for image captions

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#537]
@jamsden I am trying not to get picky but this seems really wrong:

![image](https://user-images.githubusercontent.com/64734/132863595-5df1a605-29ac-4dba-8f9b-30c4d27c6516.png)

**Comment by jamsden** [comment]
Should be no problem correcting this so that the figure caption has proper format.

**Comment by berezovskyi** [comment]
Just asked Paul about this in https://issues.oasis-open.org/browse/TCADMIN-4057?focusedCommentId=79916&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-79916

**Comment by paul-knight** [comment]
Yes, it will be allowed to fix the caption formatting - I agree h2 is not the best!

**Comment by berezovskyi** [comment]
Fixed during the publication.
