### ISSUE TITLE
Determine how oslc-op specifications will be published

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#55]
oslc-op specifications are currently process by ReSpec. Unfortunately, GitHub will not directly render HTML or handle content negotiation of any kind, it will only provide access to the text source. 

There have been various services we have used in the past to create URLs to GitHub resources that will get rendered as HTML, properly running ReSpec. One popular solution was [rawgit](https://rawgit.com). Unfortunately rawgit may not be available much longer, and we need stable URLs for published documents. 

OASIS already publishes WD, CSD, CS and OASIS Standard documents in http://docs.oasis-open.org, and will continue to do so for Project Specifications. We should leverage this and decouple published documentation from source code management.

What we need to do is determine a process for publishing oslc-op Project Specification (including drafts). That process consists of three parts:

1) Publishing the rendered ReSpec content at a stable URI that includes document status and revision information.

OASIS Committee Specification naming guidelines encode the document status indicator and revision information into multiple parts of the URI path and file parts. Unfortunately this prevents the use of relative URLs in the specification resources and requires manual processing of ReSpec generated files in order to fix the broken links.

We suggest a change in the naming guidelines to only include specification status and revision information in the path name, leaving the folder and file naming structure unchanged on publish to that relative links between parts of multi-part specifications are valid after publishing.

2) Publishing the vocabularies to open-services.net namespaces.

This should only be done on approved Project Specifications these vocabularies are used by production tools.

3) Publishing the vocabulary Resource Shape constraints

These should be published as separate versions, using the naming conventions described in the OSLC Core Overview specification.

We would like this publishing process to be completely scripted and require no manual editing or intervention. This is to ensure there are no barriers to frequently publishing draft specifications for public consumption.

**Comment by jamsden** [comment]
We have discussed where the OSLC specs should be published. OASIS indicated the normative specifications are in the GitHub repo, and the published documents are for rendering convenience, to establish URL naming conventions, and/or to ensure preservation of the specs in the even the GitHub repos are lost.

I propose the following URLs (using the QM spec as an example:
```
    edDraft: :https://raw.githack.com/oslc-op/oslc-specs/master/specs/qm/quality-management-spec.html",
    thisVersion: "https://open-services.net/specifications/qm/v2.1/psprd01/quality-management-spec.html",
    previousVersion: <whatever it was>
    latestVersion: "https://open-services.net/specifications/qm/quality-management-spec.html",
open-services.net/spec/core/oslc-core.html
```
OASIS can then provide redirects to these resources using whatever URLs they want.

Do we agree?

**Comment by ndjc** [comment]
The above is a subset of what was discussed in last week's meeting. I have written a wiki page about this - see https://github.com/oslc-op/oslc-admin/issues/6#issuecomment-505987900, and https://github.com/oslc-op/oslc-specs/wiki/URIs-in-Specifications.

Note that under the proposal as described by Andrew and myself, we would never link directly to raw.githack.com - all such links would go via a redirect from open-services.net.

Also note that the ReSpec conf variables for thisVersion and latestVersion need not be set under this proposal - ReSpec will generate the URIs automatically from other variables. previousVersion may still be set if required.

**Comment by berezovskyi** [comment]
I think we also figured this out too.
