### ISSUE TITLE
Abstract for OSLC EMS is missing

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#57]
The abstract for OSLC EMS isn't present on (https://archive.open-services.net/wiki/estimation-and-measurement/Estimation-and-Measurement-Service-Version-1.0_-REST-API/index.html)

**Comment by berezovskyi** [comment]
I will let Jim decide but I guess you just migrate all you can and leave the rest for the future editor to fix?

**Comment by jamsden** [comment]
We can get to EMS updates when someone expresses interest in the domain and wants to contribute.

**Comment by berezovskyi** [comment]
Low-prio spec; on hold.
