### ISSUE TITLE
EMS serviceRoot link is broken.

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#58]
EMS service root link is returning 404. (https://archive.open-services.net/bin/oops/Main/http:/open-services/net/Main/MetricsEmsService)

**Comment by FabioRNT** [comment]
Found the right link.

**Comment by berezovskyi** [comment]
Fpr the record, https://open-services.net/bin/view/Main/MetricsEmsService should redirect to the right page.
