### ISSUE TITLE
Couldn't find contributors for OSLC EMS

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#59]
Couldn't find the contributors to add on OSLC EMS v1 spec. (https://archive.open-services.net/wiki/estimation-and-measurement/Estimation-and-Measurement-Service-Version-1.0_-REST-API/index.html)

**Comment by berezovskyi** [comment]
Lead: https://archive.open-services.net/workgroups/estimation-and-measurement/index.html

Members: https://archive.open-services.net/bin/view/Main/MetricsMeetings.html

Otherwise  @jamsden knows more.

**Comment by berezovskyi** [comment]
Plus, for the record: https://archive.open-services.net/pipermail/oslc-steeringcommittee_open-services.net/2013-May/000205.html and https://archive.open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2

**Comment by berezovskyi** [comment]
There is some info under https://oslc-op.github.io/oslc-specs/specs/ems/estimation-measurement-spec.html#acknowledgements
