### ISSUE TITLE
ReSpec adds the HTML extension twice

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#60]
From https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-vocab.html:

![image](https://user-images.githubusercontent.com/64734/60279907-3930e200-9902-11e9-9b82-64fc70d6f3aa.png)

**Comment by jamsden** [comment]
This was a manual copy/paste error, ReSpec didn't generate these URLs. This is a good example of why we need ReSpec to generate them - they're really hard to manage manually. Fixed.
