### ISSUE TITLE
OSLC Configuration Management: oslc_config.context missing in vocabulary

### ISSUE THREAD

**Issue by MartinUlrich** [oslc-op/oslc-specs#601]
oslc_config.context as specified in  https://docs.oasis-open-projects.org/oslc-op/config/v1.0/ps01/config-resources.html#configcontext is missing in the vocabulary

**Comment by jamsden** [comment]
oslc_config.context is an HTTP query parameter, not a vocabulary term. So it wouldn't appear in the vocabulary or shapes.
