### ISSUE TITLE
RM spec incorrectly says it's PS 01

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#62]
PS is the final version of the spec. The RM 2.1 spec right now is a PSD without a number because it has not been published as a PSD yet.

**Comment by berezovskyi** [comment]
See https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-spec.html and https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-vocab.html

**Comment by jamsden** [comment]
Yes, I think ReSpec has too many specStatus values. Looks like it should only be:

- WD
- PSD
- PS
- COS
- OS

There are no public review drafts anymore, and only the COS (Candidate Oasis Standard) gets a 60 day public review.

I will update specStatus for all documents to PSD.

In theory, some of the OSLC committee specifications have already gone through public review, and changing to open project specifications shouldn't require another public review to be COS. But we did fix some errors in CM and RM, and so we should probably get all specs to PSD, then PS quickly - simply getting the content and formatting acceptable to OASIS, then submit them all as COS for public review together.

**Comment by jamsden** [comment]
Only PSPRD and PNPRD should be removed, the others are all ok.

**Comment by jamsden** [comment]
Fixed, all are set to PSD, which should be the specStatus of anything we are currently working on.

**Comment by berezovskyi** [comment]
Thanks!

I like the new set of states. Just a note: you should update the statuses to WD. They will become PSDs only after PGB approval.

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 8:28 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I think ReSpec has too many specStatus values. Looks like it should only be:

  *   WD
  *   PSD
  *   PS
  *   COS
  *   OS

There are no public review drafts anymore, and only the COS (Candidate Oasis Standard) gets a 60 day public review.

I will update specStatus for all documents to PSD.

In theory, some of the OSLC committee specifications have already gone through public review, and changing to open project specifications shouldn't require another public review to be COS. But we did fix some errors in CM and RM, and so we should probably get all specs to PSD, then PS quickly - simply getting the content and formatting acceptable to OASIS, then submit them all as COS for public review together.

**Comment by berezovskyi** [comment]
Sorry, I have no idea why a reply didn’t get through earlier, but everything in progress should have a WD status.

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 10:36 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed, all are set to PSD, which should be the specStatus of anything we are currently working on.

**Comment by jamsden** [comment]
Possibly, but we usually set the specStatus, revision and publishDate to the values we are working towards. It.s the tagging in the repo that manifests the result of the vote, not the editing. Also in this case, except for QM, all the documents were already Committee Specifications that are being migrated to OP. All have gone through public review and all probably could be COS as a result - with different revisions as needed to address final changes. I thought we could take them through the process starting with PSD - since we want a new public review on at least Core (because of conformance section) and RM (because of vocab changes). And QM needs to go through the process.

**Comment by berezovskyi** [comment]
And that's what I suggested to change. The specs shall always be a WG and only become a PSD or another status just in one "release" commit and then revert back to the WG. I think Nick was also in favour of the idea.


--
/Andrew
________________________________

**Comment by jamsden** [comment]
Let's discuss it. In the past, HEAD on master reflected the most recent status, revision and publish date of the document. Publishing was a separate step resulting in a snapshot copy. So there's no ambiguity. Version labels and open-services.net links also ensure users know what they are looking at. Anything on HEAD should be assumed to be changing, see the history if you want to know how. So having HEAD reflect the last approved status as opposed to depreciating to WD seems reasonable to me, and what we have practiced in the past.

**Comment by ndjc** [comment]
I probably won't bother removing PSPRD or other states from ReSpec - you can just not use them, and remove them from the list in the templates.

**Comment by ndjc** [comment]
For publishing, note that at least in theory, ReSpec supports a way to set conf variables by adding a query string to a URI. So one can use the URI for a document which internally says it is a WD, but then add a query string that sets the status to PSD and also sets the publication date. When the browser shows the result with the PSD status and date, you can then generate the HTML from that dynamic instance. The git source would not need to be changed and reverted.
We need to test that, and to ensure there are overridable conf variables for everything you'd want to change for publication.

**Comment by berezovskyi** [comment]
There was always ambiguity. If I looked at the SVN trunk version, I saw the publication date and the status that should have been the last modification date of the working draft. I saw the wrong date and status. I do so now on the Git HEAD.

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 5:58 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Let's discuss it. In the past, HEAD on master reflected the most recent status, revision and publish date of the document. Publishing was a separate step resulting in a snapshot copy. So there's no ambiguity. Version labels and open-services.net links also ensure users know what they are looking at. Anything on HEAD should be assumed to be changing, see the history if you want to know how. So having HEAD reflect the last approved status as opposed to depreciating to WD seems reasonable to me, and what we have practiced in the past.

**Comment by berezovskyi** [comment]
But you can’t rely on external links to ensure consistency! Neither version labels on Github nor links on oslc.co are a substitute for the correct info on the spec page itself!

Having said that, without a build it will be impossible to produce the right dates on the fly. We can remove them from the working drafts (I don’t need the spec to tell me what is the day today, it just misleads me into believing the spec was updated just today). But for PSDs we would then have to set the date in a release commit (and remove it back). Which is fine.

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 5:58 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Let's discuss it. In the past, HEAD on master reflected the most recent status, revision and publish date of the document. Publishing was a separate step resulting in a snapshot copy. So there's no ambiguity. Version labels and open-services.net links also ensure users know what they are looking at. Anything on HEAD should be assumed to be changing, see the history if you want to know how. So having HEAD reflect the last approved status as opposed to depreciating to WD seems reasonable to me, and what we have practiced in the past.

**Comment by berezovskyi** [comment]
Sounds fine

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 7:39 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


I probably won't bother removing PSPRD or other states from ReSpec - you can just not use them, and remove them from the list in the templates.

**Comment by berezovskyi** [comment]
Wow, that sounds interesting. And dangerous  💣

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 7:43 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


For publishing, note that at least in theory, ReSpec supports a way to set conf variables by adding a query string to a URI. So one can use the URI for a document which internally says it is a WD, but then add a query string that sets the status to PSD and also sets the publication date. When the browser shows the result with the PSD status and date, you can then generate the HTML from that dynamic instance. The git source would not need to be changed and reverted.
We need to test that, and to ensure there are overridable conf variables for everything you'd want to change for publication.
