### ISSUE TITLE
RM spec links are broken

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#63]
https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-vocab.html and https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-spec.html

![image](https://user-images.githubusercontent.com/64734/60280728-d04a6980-9903-11e9-964c-b2887830f1c7.png)

Checked with https://chrome.google.com/webstore/detail/broken-link-checker/nibppfobembgfmejpjaaeocbogeonhch

**Comment by berezovskyi** [comment]
https://oslc-op.github.io/oslc-specs/specs/rm/requirements-management-spec.html

https://oslc-op.github.io/oslc-specs/specs/rm/requirements-management-vocab.html

**Comment by jadelkhoury** [comment]
Suggested plugin for broken links was no good. using https://addons.mozilla.org/en-GB/firefox/addon/find-broken-links for firefox instead
