### ISSUE TITLE
Update templates to new OSLC OP template

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#67]
There are a number of templates in the oslc-specs/templates folder. Some of these are probably sufficiently out of date that they can be discarded. Others need to be updated for the new Project Specification format, and to include the conformance section. 

Since we don't plan on creating too many more new OSLC specifications, this can be a low priority activity. On the other hand, editing these templates might be a great way to formalize what we expect the Project Specification format source for ReSpec to be.

**Comment by jamsden** [comment]
OASIS should be providing the OP PS(D) template soon. Once we have that we can retrofit in ReSpec for our new templates and delete these old ones.

**Comment by berezovskyi** [comment]
Ok

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 9:44 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


OASIS should be providing the OP PS(D) template soon. Once we have that we can retrofit in ReSpec for our new templates and delete these old ones.

**Comment by ndjc** [comment]
I do not understand the comment about getting a new OP PS template. I thought that's what I had been working on for a couple of weeks now.
And I have been updating some of those templates with required ReSpec changes, and expect to complete doing that as part of the ReSpec work.

**Comment by jamsden** [comment]
I understand Nick, and share your concern. But I don't think OASIS has provided the final OP template yet. So not only is it possible there will be additional changes now, but experience has shown the template and conforming spec formats change over time.

I we can expect to have to maintain ReSpec appropriately. Hopefully these changes will be mostly cosmetic and easy to do.

Ultimately it will come down to how flexible OASIS is in accepting PSDs for publication as PSs.

**Comment by berezovskyi** [comment]
If I am not mistaken, only Nick makes changes to the ReSpec template. I don’t think we should be waiting for any other kind of template.

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 7:08 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not understand the comment about getting a new OP PS template. I thought that's what I had been working on for a couple of weeks now.
And I have been updating some of those templates with required ReSpec changes, and expect to complete doing that as part of the ReSpec work.

**Comment by berezovskyi** [comment]
@chet-ensign, could you please comment on this?

**Comment by berezovskyi** [comment]
Me and Nick made like 99% of the changes requested by OASIS. Will track new change requests separately.
