### ISSUE TITLE
Working drafts shall be clearly marked

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#71]
When I set the following properties:

```js
var respecConfig = {
  specStatus : "WD",
  revision: "02",
  //publishDate:  "",
  previousPublishDate:  "2018-05-31",
  previousMaturity:  "CSD",
}
```

I expect the subtitle to contain "Working Draft" or "Working Draft 02" and the last modification date of the webpage. Instead, I only see the date. The status is buried deep inside.

**Comment by berezovskyi** [comment]
@jamsden I think these are the semantically correct properties of the RM spec draft at the moment.

**Comment by jamsden** [comment]
RM was a CS.

**Comment by berezovskyi** [comment]
Fixed

**Comment by ndjc** [comment]
Fix merged into master
