### ISSUE TITLE
Core spec has 17 HTML5 validation errors

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#72]
With https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif, I get 17 HTML5 errors in the Core spec.

<details>
<summary>HTML5 validity report</summary>

VM94:1 line 191: Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
(anonymous) @ VM94:1
VM94:1 line 196: Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
(anonymous) @ VM94:1
VM94:1 line 197: Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
(anonymous) @ VM94:1
VM94:1 line 254: Consider using the “h1” element as a top-level heading only (all “h1” elements are treated as top-level headings by many screen readers and other tools).
(anonymous) @ VM94:1
VM94:1 line 280: Element “br” not allowed as child of element “dl” in this context. (Suppressing further errors from this subtree.)
(anonymous) @ VM94:1
VM94:1 line 281: Element “p” not allowed as child of element “dl” in this context. (Suppressing further errors from this subtree.)
(anonymous) @ VM94:1
VM94:1 line 337: Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
(anonymous) @ VM94:1
VM94:1 line 352: No “p” element in scope but a “p” end tag seen.
(anonymous) @ VM94:1
VM94:1 line 420: End tag “div” seen, but there were open elements.
(anonymous) @ VM94:1
VM94:1 line 416: Unclosed element “section”.
(anonymous) @ VM94:1
VM94:1 line 416: Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
(anonymous) @ VM94:1
VM94:1 line 725: No “p” element in scope but a “p” end tag seen.
(anonymous) @ VM94:1
VM94:1 line 776: The “cellspacing” attribute on the “table” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 776: The “cellpadding” attribute on the “table” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 776: The “border” attribute on the “table” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 779: The “width” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 779: The “valign” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 781: The “width” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 781: The “valign” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 783: The “width” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 783: The “valign” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 785: The “width” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 785: The “valign” attribute on the “td” element is obsolete. Use CSS instead.
(anonymous) @ VM94:1
VM94:1 line 2: This document appears to be written in English. Consider adding “lang="en"” (or variant) to the “html” start tag.

</details>

**Comment by jamsden** [comment]
Resolved by https://github.com/oslc-op/oslc-specs/pull/360
