### ISSUE TITLE
Inconsistency between dcterms:identifier cardinality

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#77]
RM spec requires it to be 0..1
CM spec requires 1..1

nothing illegal, but should be looked at carefully

**Comment by berezovskyi** [comment]
Similar inconsistency in the `oslc:instanceShape` cardinality:

0..1 in RM
0..* in CM

**Comment by jamsden** [comment]
That's they way they are in the 2.0 specifications. Domain specs do have the right to tighten or loosen these constraints. Re dcterms:identifier, if RM servers don't use it for identity, then 0..1 is fine. Re instanceShape, 0..* is more general, but 0..1 is probably the most common.

**Comment by jadelkhoury** [comment]
Agree! For RM, I just made sure 2.1 matches 2.0. So, do we close this issue?

**Comment by jamsden** [comment]
I suggest we check with Ian Green and see if these were mistakes.

**Comment by jamsden** [comment]
I think we can close this. I don't like the inconsistency, but its not that significant and I don't see any reason to introduce a possible inconsistency between the versions of the same spec.
