### ISSUE TITLE
oslc_cm:approved is missing from the vocabulary section

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#78]
The property is used in the shapes but not declared earlier.

**Comment by berezovskyi** [comment]
same for `oslc_cm:closed`

**Comment by berezovskyi** [comment]
same for `oslc_cm:fixed`

**Comment by berezovskyi** [comment]
same for `oslc_cm:inProgress`

**Comment by berezovskyi** [comment]
same for `oslc_cm:reviewed`

**Comment by berezovskyi** [comment]
same for `oslc_cm:verified`

**Comment by jamsden** [comment]
these are defined in the vocabulary ttl.

**Comment by berezovskyi** [comment]
great! then it's only the spec that needs to be fixed

**Comment by jamsden** [comment]
See commit: 136c50dda1f1301217669cc24a971d4119ed5664, the vocabulary terms were defined in but were missing their type a:Property, and so ReSpec wasn't publishing them. This is fixed now.
