### ISSUE TITLE
Does it make sense for a Defect to implement a Requirement?

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#79]
I don't think it makes sense for a defect to be _required_. I think someone did a bit too much of OO modelling with this one. Removing it would cause some impl trouble but will better reflect semantics of the Defect resource.

**Comment by jamsden** [comment]
Not sure of the context. Is this CM 3.0 (which defines Defect as a subclass of ChangeRequest).

Re: Requirement implementedBy ChangeRequest | Defect - I guess that's fine. A ChangeRequest represents work that needs to be done to accomplish something. Requirements generally are satisfied, not implemented. But this is already in OSLC 2.0 so we can't change it now.

**Comment by jamsden** [comment]
The Requirement implementedBy ChangeRequest triple would indicate that the completion of the work specified in the change request is what implements the requirement, not the change request itself. The same would be true of a Defect. It is the resolution of the defect that implements the requirement, not the defect itself.

**Comment by berezovskyi** [comment]
But I don't expect you have requirements for defects to be resolved? But let's keep it as it is if you wish so.
