### ISSUE TITLE
oslc_qm:executionInstructions defines occurs, but the comment indicates it shouldn't

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#80]
The comment says: "Instructions for executing the test script. Note that the value of Occurs is undefined. The resource shape document provided by the QM service provider may be consulted for its value."

Not sure why this is, but perhaps the shape for that property should not define the occurs value.

**Comment by jamsden** [comment]
Commenting out the oslc:occurs property of property oslc_qm:executionInstructions results in no change in the property table. Look like ReSpec us using Zero-or-more as the default. 

In any case, the oslc:occurs property was specified in the shapes we got from the existing RQM implementation, and specifying Zero-or-more doesn't constrain a server in any significant way. I think this can be closed with no change.

**Comment by berezovskyi** [comment]
I agree, 0..* is equivalent to *.
