### ISSUE TITLE
Core puts booleans in quotes in examples

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#83]
Example from CS01:

```
colorConstraint
    a oslc:Property ;
    oslc:name "color" ;
    dcterms:description "The colors for a traffic light as specified by FHWA."
    oslc:propertyDefinition color ;
    oslc:occurs oslc:Exactly-one ;
    oslc:range Color ;
    oslc:allowValue red, yellow, green ;
    oslc:readOnly "false" ;
    oslc:representation oslc:Reference ;
    oslc:valueType oslc:Resource .
```

This is wrong: https://www.w3.org/TR/turtle/#booleans

**Comment by jamsden** [comment]
Should ShapeChecker detect these? Or is false or "false" accepted?

**Comment by berezovskyi** [comment]
ShapeChecker does not check HTML specs.

**Comment by jamsden** [comment]
Oops, I didn't see you mentioned examples. By the way, the shape .ttl files use  "false"^^xsd:boolean. Should these be changed too?

**Comment by jamsden** [comment]
Fixed. That was the only one that didn't also use  "false"^^xsd:boolean.

**Comment by berezovskyi** [comment]
There is no need for "false"^^xsd:boolean. As the linked spec says, just drop the quotes.
