### ISSUE TITLE
RM shapes are missing

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#84]

**Comment by jamsden** [comment]
What shapes are missing?

**Comment by berezovskyi** [comment]
All of 'em. Requirement? RequirementCollection?

**Comment by jamsden** [comment]
https://github.com/oslc-op/oslc-specs/blob/master/specs/rm/requirements-management-shapes.ttl. If they're not showing up in requirements-management-vocab.html, then its probably a ReSpec error. The work for me at the moment, but I might be using a different ReSpec than you are.

**Comment by berezovskyi** [comment]
got it too, thanks!
