### ISSUE TITLE
Two RM vocabs exist

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#85]
See specs/rm/requirements-management-vocab.ttl and specs/rm/rm.ttl

**Comment by ndjc** [comment]
I believe rm.ttl is a Turtle translation of rm.xml, which is a very old prototype of the RM vocabulary. I strongly suspect neither is required any longer - but @img should confirm.

**Comment by jamsden** [comment]
I pulled rm.rdf from https://archive.open-services.net/ns/rm/rm.rdf and added it to the GitHub folder. It is my recollection that I used this file to create requirements-management-vocab.ttl. I don't recall where rm.xml came from. It is not the same content as rm.rdf, but that could be from transformations and sorting.

**Comment by berezovskyi** [comment]
I will write a short Groovy script to check the isomorphism of RDF graphs from those 3 files in Jena and report back.

**Comment by berezovskyi** [comment]
I have converted all three vocabs into pretty Turtle with Jena's RIOT tool (`riot --formatted=turtle requirements-management-vocab.ttl > rm_vocab.ttl` and so on) and can confirm that `rm.ttl` and `rm.xml` contain isomorphic RDF graphs.

Current `requirements-management-vocab.ttl` is twice as short and has a number of properties removed (as being discussed in #86). It also refactors `<http://open-services.net/ns/rm#satisfiedBy>` into prefixed URIs.

If we agree to make Turtle files normative, I suggest we remove the RDF/XML file. Also, as per #86, I also expect the removed properties to be restored (we are in agreement on that with Ian; whether they get subsequently obsoleted is another question).

**Comment by jamsden** [comment]
Agree

**Comment by jamsden** [comment]
@berezovskyi, check rm.rdf - this is the RM 2.0 vocabulary that was published on open-services.net. Ideally RM 2.1 would be compatible with this. 

I thought I created rm.ttl from this, but I don't remember. Then requirements-management-vocab.ttl was created from that with some editing. But this was long enough ago that I don't remember the details.

**Comment by berezovskyi** [comment]
@jamsden preliminary results with Jena's `rdfcompare` tool:

```
$ rdfcompare rm.rdf rm.xml RDF/XML RDF/XML
models are unequal
```

**Comment by berezovskyi** [comment]
All right, here is the more complete analysis:

- rm.rdf is really wrong as it is missing the inverse properties defined in the RM 2.0 spec. As Ian said, spec takes priority in RM 2.0. Futher, literals had many newlines and were marked with `en` language, which will make it hard to query the file via SPARQL.
- the current vocab file cleans up the Turtle file but is still the same as rm.rdf, missing all the inverse properties.
- the rm.xml is fully equivalent to rm.ttl and contains all the properties from the spec and some of the current vocab refactoring (eg the definition of the ontology but not the literal fixes or the use of namespaces)

I have opened a PR #119 to work through all those files and to replace the current vocab with Jim's vocab while applying all the refactorings.

**Comment by jamsden** [comment]
OK, so this fits with my memory: I started with rm.rdf, created rm.xml and rm.ttl from that, migrated rm.ttl to requirements-management-vocab.ttl and shapes.ttl, and must have removed the inverse properties (although I don't remember that). So we're good - just add the missing properties to requirements-management.vocab.ttl and shapes.ttl so it matches RM 2.0 spec and we're good.

**Comment by berezovskyi** [comment]
Jad will remove extra vocabs after the review
