### ISSUE TITLE
RM vocab removes inverse properties

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#86]
Related to #85 and #82.

I assume this is the normative vocab: specs/rm/requirements-management-vocab.ttl

The properties already in use since 2.0 shall not be removed.

**Comment by jamsden** [comment]
This should be subject to Ian Green's review. It's possible that this was specified, but intentionally not implemented and expected to be deprecated in a future version of the RM spec, given the link guidance. 

https://archive.open-services.net/bin/view/Main/RmVocabulary.html does not define these vocabulary terms either, and they are not defined in https://archive.open-services.net/ns/rm/rm.rdf.

So the RM 2.0 specification (and the hand-created HTML shape tables) does not align with the published vocabulary. It is not clear how this should be resolved. We need input from Ian.

If we decide the RM 2.0 spec is normative, then can't remove these properties, we can only deprecate them (if that's what we decide to do). The following properties are missing in RM 2.1 that are in RM 2.0 spec (but not the vocabulary currently published on open-services.net/ns):
* constrainedBy
* constrains
* decomposedBy
* decomposes
* elaborates
* satisfies
* specifies

These all need to be added back to requirements-managerment-vocab.ttl. Other than the spelling errors (which I think I created), the vocabulary definitions can be copied from rm.ttl

**Comment by berezovskyi** [comment]
> this was specified, but intentionally not implemented

As long as it was ever released in a normative section of a published spec, it's there.

> expected to be deprecated in a future version of the RM spec

Fine. But deprecated != erased. @ndjc has a good rdf property to indicate deprecation at the vocabulary level.

**Comment by berezovskyi** [comment]
> If we decide the RM 2.0 spec is normative, then can't remove these properties

That's exactly how I see it.

**Comment by jamsden** [comment]
The issue is I don't know what's right - the RM 2.0 spec, or the published RM 2.0 vocabularies on open-services.net/ns/rm. Ian would know.

**Comment by berezovskyi** [comment]
I think the spec is spec shall be considered normative.

The spec actually says that the published files have precedence over the spec text.

Finally, the document published on the website theoretically has the lowest precedence.

Practically speaking, I expect the document to take precedence over files in case of a major discrepancy. I also expect not to remove or semantically alter the definitions published on open services for a long while.

Does it make sense?

--
/Andrew
(from phone)

18 juli 2019 kl. 23:10 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


The issue is I don't know what's right - the RM 2.0 spec, or the published RM 2.0 vocabularies on open-services.net/ns/rm<http://open-services.net/ns/rm>. Ian would know.

**Comment by img** [comment]
I'm not sure I understand the issue.

The initial release of the RM spec (https://archive.open-services.net/bin/view/Main/RmSpecificationV26954.html?rev=46) omitted a few properties which were added in September 2012 (see https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html).

specs/rm/rm.ttl contains these changes, but specs/rm/requirements-management-vocab.ttl does not. I don't know the provenance of these files.

I would speculate that the rm.rdf file on open-services.net was not updated when the properties were added (I can only find the initial revision).  Someone subsequently created/updated rm.ttl accordingly as part of the move to OASIS.

**Comment by img** [comment]
If the issue is the discrepancy between rm.rdf and RmSpecificationV2, then the specification wins.

**Comment by berezovskyi** [comment]
Thanks a lot, Ian!

Just to be clear: by saying “omitted”, you mean that those properties should have been there in the initial release and shall not be silently removed from 2.1, correct?

--
/Andrew
(from phone)



On Fri, Jul 19, 2019 at 10:35 AM +0200, "img" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure I understand the issue.

The initial release of the RM spec (https://archive.open-services.net/bin/view/Main/RmSpecificationV26954.html?rev=46) omitted a few properties which were added in September 2012 (see https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html).

specs/rm/rm.ttl contains these changes, but specs/rm/requirements-management-vocab.ttl does not. I don't know the provenance of these files.

I would speculate that the rm.rdf file on open-services.net was not updated when the properties were added (I can only find the initial revision). Someone subsequently created/updated rm.ttl accordingly as part of the move to OASIS.

**Comment by img** [comment]
that's correct @berezovskyi.

**Comment by jamsden** [comment]
That makes sense Ian. I think I discovered the missing properties in rm.rdf on open-services.net and added them (with a couple of spelling errors) in specs/rm/rm.ttl a long time ago. But it looks like these didn't get added to requirements-management-vocab.ttl - I don't know why. 

But that still leaves the question about whether we should make these "dual properties" as deprecated since they do not follow link guidance (regarding backlinks) that probably evolved after the RM 2.0 spec was updated. 

I suggest we 1) add these properties back to requirements-management-vocab.ttl, but mark them as archaic in the vocabulary and reference the link guidance to explain why. If we decide not to mark them as archaic, then perhaps we should add a SHOULD to guide server implementations to avoid redundant backlinks. This will cause real problems for configuration management.

I think  this may require a PGB vote to ensure we are all in agreement on this change.

**Comment by berezovskyi** [comment]
@img what do you think about deprecating those properties in the next revision of the spec?

**Comment by berezovskyi** [comment]
e.g. https://docs.oasis-open.org/oslc-domains/cm/v3.0/cs02/part2-change-mgt-vocab/cm-v3.0-cs02-part2-change-mgt-vocab.html#affectsTestResult

**Comment by jamsden** [comment]
We agreed that these "inverse" properties are not a problem, and do not violate link guidance. Link guidance is for server implementations, not necessarily specifications. As long as the cardinality lower bound of these properties is 0, servers can decide which property to support (neither, either, or both) and how to store and manage them. Inverse properties are by themselves not an issue, and are a normal part of OWL. What link guidance is attempting to address is not whether links have inverses or not, but that server implementations shouldn't store redundant information that can get out of sync.

The properties defined in the RM 2.0 open-services.net spec should be added back to the requirements-management-vocab.ttl and requirements-management-shapes.ttl files. 

We should also understand any differences between the rm.rdf vocabulary that was published on open-services.net/ns and the RM 2.0 spec as these should be the same. Any differences should be raised as an issue and resolved.

**Comment by berezovskyi** [comment]
I will do some more checks on the file you recently pushed and will report the results here.

--
/Andrew
(from phone)

15 aug. 2019 kl. 19:42 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


We agreed that these "inverse" properties are not a problem, and do not violate link guidance. Link guidance is for server implementations, not necessarily specifications. As long as the cardinality lower bound of these properties is 0, servers can decide which property to support (neither, either, or both) and how to store and manage them. Inverse properties are by themselves not an issue, and are a normal part of OWL. What link guidance is attempting to address is not whether links have inverses or not, but that server implementations shouldn't store redundant information that can get out of sync.

The properties defined in the RM 2.0 open-services.net<http://open-services.net> spec should be added back to the requirements-management-vocab.ttl and requirements-management-shapes.ttl files.

We should also understand any differences between the rm.rdf vocabulary that was published on open-services.net/ns<http://open-services.net/ns> and the RM 2.0 spec as these should be the same. Any differences should be raised as an issue and resolved.
