### ISSUE TITLE
Merging OSLC repositories

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#9]
If we want to preserve all the commit history, we should follow the advice outlined here: https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by berezovskyi** [comment]
cc @jamsden

**Comment by berezovskyi** [comment]
Jim, I think you will bring it up with Chet so I can keep the issue assigned to you until you come back to us with a response?

**Comment by jamsden** [comment]
That fine. I'm hoping we can rename the core repo, and then just migrate domains. Core already has all the tools.

**Comment by berezovskyi** [comment]
Sounds like a plan. Tell me once you discuss it with Chet and I can merge the git history of the domains repo into this one.

--
/Andrew

17 jan. 2019 kl. 18:56 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


That fine. I'm hoping we can rename the core repo, and then just migrate domains. Core already has all the tools.

**Comment by berezovskyi** [comment]
done
