### ISSUE TITLE
Deprecate Atom representations

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#92]
OSLC QM spec still says the servers SHOULD implement Atom serialisation. I think OSLC 3 should deprecate that serialisation in favour of RDF/XML serialisation that does the job pretty well.

https://archive.open-services.net/bin/view/Main/OSLCCoreSpecAppendixRepresentations#Atom_Representations

**Comment by berezovskyi** [comment]
> application/atom+xml QM servers should respond with Atom Syndication Format XML representation as defined in the OSLC Core Representations Guidance [qm-29]

**Comment by berezovskyi** [comment]
I propose to change this as follows:

> `application/atom+xml` QM servers **MAY** support Atom Syndication Format XML representation as defined in the OSLC Core Representations Guidance to maintain integrations with the legacy applications [QM-29].

**Comment by ndjc** [comment]
OK with me.

**Comment by berezovskyi** [comment]
Thanks Nick. Reassigning to @graybachelor as the spec editor (I can make the PR if you wish).

**Comment by berezovskyi** [comment]
QM 1.0 declares it a MUST: archive.open-services.net/bin/view/Main/QmRestApiV1.html#Get_a_collection_of_QM_resources

Are we planning to fix in v2.1 the v1.0 MUST dropped in v2.0?

**Comment by ndjc** [comment]
Why would we do that? Surely, we want to phase out OSLC 1. The community has lived quite happily with QM 2.0 and a SHOULD for atom for many years now, and I see no problem in dropping even that SHOULD in 3.0. Servers that want 1.0 compatibility can still support atom if they want.

**Comment by berezovskyi** [comment]
I would love go forward with my original proposal to mark it MAY to support legacy apps.

I hope @jamsden is OK with this.

**Comment by jamsden** [comment]
I'm not personally aware of any specific uses of Atom with our QM apps. However, it is a standard representation for RSS readers, and I could see that as being useful for reporting testing results. 

Deprecating SHOULD to MAY seems ok to me in general though, especially if we don't know of any usages of Atom. But I don't really see the motivation for making the change either.
